### PR TITLE
Blackjack project

### PR DESCRIPTION
**Pull request by antalnorbert95**
I've implemented the requirements, but I'm not sure if correctly. 
The program in its current form has a lot of bugs.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Great work! it looks good and you can play it just fine. There are however some minor things which you have to look into and some "major" things which you'll have to further include.

**Comment by Alex-Cosma** [comment]
Minor things:
- the `hit` and `stand` buttons should not appear unless a game is ongoing
- classes should be separated in packages

**Comment by Alex-Cosma** [comment]
Major things:
- I want you to implement a menu for this game. You should make it so that you can play as a guest, or login with your own account -> keep a score for each existing account. You can keep these scores by actually saving through serialization a list of Account objects (class which you'll have to create) and loading it each time on program startup. Check out [this tutorial](http://beginnersbook.com/2013/12/how-to-serialize-arraylist-in-java/) on how to save/load an array list to a file

- You should make it in such a way that more than 2 players (2-4) are able to play. Of course, you can leave all of them except yourself as computer players, but they should appear on the left and right side of the screen. Sure, you can move and resize your buttons such that this new requirement will fit the screen.

- Also, in the menu, you should be able to select the number of players which the game will use. Right now, it's always 2 players (you + dealer) but it could be a maximum of 4 players (3 + dealer)


Again, looking very promising so far!

**Comment by Alex-Cosma** [comment]
Ok, yes, better. I have a few observations however.

You see there is no clear place in your code which defines a "Player". There is `Player` class, nothing to represent something which, to be fair, is of fairly high importance for a game, right? 
I see that in your `Controller` class, you have something like 

```
	private List<ArrayList<Card>> playerHands = new ArrayList<ArrayList<Card>>();
```

which yes, represents a list of lists of cards, one list for each player. Mkay, yea, sure, but again, I think that things like these should be somehow enclosed in a `Player` class. This class should hide away and encapsulate the behaviour of a player. And then, in the controller class, you will have a list of `Player` instances, not of `List<Card>`

Use your imagination here. I am only pointing you into a direction

**Comment by Alex-Cosma** [comment]
There is also an error which occurs when a game has started and you only after change the number of players, by the way

**Comment by Alex-Cosma** [comment]
Keep it up, you're on the right path

**Comment by Alex-Cosma** [comment]
Also, the dealer should be just another instance of this `Player` class, don't you think?

**Comment by antalnorbert95** [comment]
I am sorry, I meant "Player" class.

**Comment by Alex-Cosma** [comment]
Norbert, you never seem to disappoint. Great job, but there is a thing which kinda sortof bothers me.

**Comment by Alex-Cosma** [comment]
In the `Player` class you have:

```
	public void drawPlayer(int playerNr) {
		if (playerNr == 15) {
			board.drawDealer(hand.get(hand.size() - 1));
		} else {
			board.drawPlayer(hand.get(hand.size() - 1), playerNr);
		}
	}
```

This is somewhat confusing. Basically, you're doing different things depending on whether or not the instance of the player is a dealer, right?

Well, is there any way you can make this a bit ... cleaner? How about polymorphism? Creating a subclass `Dealer` which extends this class but implements this `draw` method differently?

**Comment by Alex-Cosma** [comment]
Overall, good work, I don't have much to add, but of course, you can always mingle with stuff yourself.  
Is there any extra functionality which you'd want to add?

**Comment by antalnorbert95** [comment]
I can't think of any extra functionality, except trying to fix the remaining bugs.

**Comment by Alex-Cosma** [comment]
Fair enough. Bug fixing it is

**Comment by antalnorbert95** [comment]
I think I fixed all the bugs I could find.

**Comment by Alex-Cosma** [comment]
Then you're pretty much done here, Norbert. Have a very merry Christmas and happy new year!

**Comment by antalnorbert95** [comment]
Merry Christmas and Happy New Year to you, too!

**Pull request merged**
