### PR TITLE
Snake Project

### PR DESCRIPTION
**Pull request by MihocNick**

### CODE REVIEW

**Comment by MihocNick** [comment]
Sorry about the double upload. Please if you can select only one commit

**Comment by Alex-Cosma** [comment]
The game is cute as a button! :blush:

**Comment by Alex-Cosma** [comment]
However, there are quite a few things which you'll need to change. 
- First off, please consider breaking your code into more than one package
- Then take a very good look at the `SnakeGame` class. It's absolutely humongous!
- Now remember, you are modelling a `Snake` game. There is a `Snake` object on the slithering around the board, yet .. curiously enough, there is no `Snake` class! :scream: 
- There's also an `Apple` object of some sort appearing randomly on the board. But there's not `Apple` class! :scream_cat: 
- On top of this, the `SnakeGame` class contains both menu related things and game logic things which all for some reason intertwine and are in the same place. Remember, *single responsibility!*

**Comment by MihocNick** [comment]
I changed some things but now my game is not working properly. Can you look over the code and give me a hint about what i did wrong?
I hope that the packages and the classes that are now are ok.

**Comment by Alex-Cosma** [comment]
No, I'm not doing bugfixing, I'm sorry...

**Comment by Alex-Cosma** [comment]
But yes, your class organization is better

**Pull request merged**
