### PR TITLE
Breakout Game

### PR DESCRIPTION
**Pull request by cosminapascaru**
I found something similar to my game and I took the canvas part from there, but I adapted it. I hope it's OK. I have 2 problems: 
1. The ball breaks all the bricks it touches and I thought it should only break one at a time. I tried something but it didn't work... so I don't really know how to do that
2. In order to remove the bricks I just changed their color to black, but they are still there and when the ball passes you can see the spaces. How can I actually remove them? I tried something with Graphics g , g.clearRect() but it was a fail ...

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
It's quite alright that you found the canvas and adapted it, yes.

**Comment by Alex-Cosma** [comment]
Your class design however is slightly too coupled in the sense that every entity knows about the whole game. I don't think that the `Entity` class should know about the `game`. Moreover, if you look at the actual entities, only the `Ball` uses that `game` object. I think you should extract that small part of code from the `Ball` class which uses the `game` object and place it somewhere else as to not have the `game` attribute at all in your `Entity` class. 
Very well designed otherwise!

**Comment by Alex-Cosma** [comment]
Now about your two problems.
1. Unfortunately, that is something you will have to investigate. It's most probably related to how your intersect detection works and how you're treating an intersection, but I cannot tell you for sure.
2. You might have to remove the brick from your `brick` array once it is destroyed. I think that would be the logical solution. Now, you might find that tricky to do when dealing with arrays (as you have an array, not a list) however, there might be another solution.

What if your `Brick` class would contain a `destroyed` boolean attribute which, initialized to false, will be set true once that certain brick is destroyed? Then, in your `Game` class you will have something like this:


```
		for (int i = 0; i < 9; i++) {
			for (int j = 0; j < 5; j++) {
				if(!brick[i][j].isDestroyed()) {                              
				brick[i][j].paintComponent(g);
				}
			}
		}

```

**Comment by Alex-Cosma** [comment]
Also, your constants (`windowWidth`, `windowHeight`) should be written with upper-case letters and using a underscore (`_`) character. 

But again, I really like what you did with the class design though. Minor things which can be improved, but otherwise, nice and clean.

**Comment by cosminapascaru** [comment]
Thank you. I will change those things and try to figure out the bricks :)

**Comment by cosminapascaru** [comment]
I corrected some things and now the ball doesn't go through the bricks like crazy. The new game is BreakoutGame 1 :)

**Comment by cosminapascaru** [comment]
Ok. I understand . Thank you

**Comment by cosminapascaru** [comment]
I have a problem with the levels. In the Game class I have a variable "level"  which is supposed to increment whenever a level is finished... It doesn't. If I change it from the beginning all levels work, but it just won't increment and I can't figure out why.

**Comment by cosminapascaru** [comment]
Forgot to add the levels ...

**Comment by Alex-Cosma** [comment]
Even though I'm more than willing to help out with the general look-and-feel of the code, I can't really bugfix it. If I were to have to do it for everyone (~75 people) it would take ages!
I'm pretty sure you can figure out on your own why that variable doesn't get incremented the way you want it to :relaxed:

**Comment by cosminapascaru** [comment]
Well, I hope. Is it OK otherwise ?

**Comment by cosminapascaru** [comment]
Solved it with "currentLevel" :)

**Comment by cosminapascaru** [comment]
Happy New Year !
I wanted to ask you if I should put the score panel in a different class, or just keep it in the Game class. Apart from that, this is the final version :) I hope it works properly

**Comment by Alex-Cosma** [comment]
You can keep it there, it's fine. That means you're done! 

Happy new year to you as well

**Pull request merged**
