### PR TITLE
Project

### PR DESCRIPTION
**Pull request by florin-popa**
I wanted to see if I am on the right path, or I have to start all over again from scratch (crossed my mind a couple of times). The algorithm for rendering from GameEngine is not mine, I tried to adapt it to my frame.

### CODE REVIEW

**Comment by florin-popa** [comment]
I noticed that when I run the game, my laptop uses a lot of resources and starts heating. When I close it, everything goes back to normal. I assume it's because of the game loop and the rendering speed, but is it normal? Can I somehow fix this issue?

**Comment by Alex-Cosma** [comment]
Please include the `.project` file into the commit as well :blush:

**Comment by florin-popa** [comment]
I would incude it, but I have no .project file. I copied the whole project folder into the private repository folder. I'm using the Eclipse IDE for MacOS, maybe that's the reason.

**Comment by florin-popa** [comment]
I could eventually import the project on Windows and then save it before I make a commit.

**Comment by Alex-Cosma** [comment]
Ooooh, you're using Eclipse for Mac! Then yes, that's why. Don't even worry about it. I'll manually import the files in a project and look over them

**Comment by Alex-Cosma** [comment]
Oh how very cool! I was about to tell you that last time - the fact that you had to perfectly position little Pacman in order to take a corner. Very nice! Great improvement. Now finish it off by making it look like the original :smile: 

ps: do be more careful with the variable names

**Comment by Alex-Cosma** [comment]
Hahaa! So cool :laughing: Best looking project so far. Here are still a few observations

**Comment by Alex-Cosma** [comment]
All your images, including the ones for little Pacman should be moved in the `res` folder. There should never be anything else than java code in the source folders.

**Comment by Alex-Cosma** [comment]
Your `Ghosts` class does things in a slight non-OOPish way, and here's what I mean.
I see a lot of duplicate code here:
```
if(dirBlue == right){
				
				if(charAt(row[0],column[0]+1) != '0'){
					column[0]+= 1;
				}else{
					dirBlue = randomGen.nextInt(4);
				}
				
			}else if(dirBlue == left){
				
				if(charAt(row[0],column[0]-1) != '0'){
					column[0] -= 1;
				}else{
					dirBlue = randomGen.nextInt(4);
				}
				
			}else if(dirBlue == up){
				
				if(charAt(row[0]-1,column[0]) != '0'){
					row[0] -= 1;
				}else{
					dirBlue = randomGen.nextInt(4);
				}
				
			}else if(dirBlue == down){
				
				if(charAt(row[0]+1,column[0]) != '0'){
					row[0] += 1;
				}else{
					dirBlue = randomGen.nextInt(4);
				}
			
			}
			
			//RED
			
			if(dirRed == right){
				
				if(charAt(row[1],column[1]+1) != '0'){
					column[1]+= 1;
				}else{
					dirRed = randomGen.nextInt(4);
				}
				
			}else if(dirRed == left){
				
				if(charAt(row[1],column[1]-1) != '0'){
					column[1] -= 1;
				}else{
					dirRed = randomGen.nextInt(4);
				}
				
			}else if(dirRed == up){
				
				if(charAt(row[1]-1,column[1]) != '0'){
					row[1] -= 1;
				}else{
					dirRed = randomGen.nextInt(4);
				}
				
			}else if(dirRed == down){
				
				if(charAt(row[1]+1,column[1]) != '0'){
					row[1] += 1;
				}else{
					dirRed = randomGen.nextInt(4);
				}
			
			}
			
			//PURPLE
			
			if(dirPurp == right){
				
				if(charAt(row[2],column[2]+1) != '0'){
					column[2]+= 1;
				}else{
					dirPurp = randomGen.nextInt(4);
				}
				
			}else if(dirPurp == left){
				
				if(charAt(row[2],column[2]-1) != '0'){
					column[2] -= 1;
				}else{
					dirPurp = randomGen.nextInt(4);
				}
				
			}else if(dirPurp == up){
				
				if(charAt(row[2]-1,column[2]) != '0'){
					row[2] -= 1;
				}else{
					dirPurp = randomGen.nextInt(4);
				}
				
			}else if(dirPurp == down){
				
				if(charAt(row[2]+1,column[2]) != '0'){
					row[2] += 1;
				}else{
					dirPurp = randomGen.nextInt(4);
				}
			
			}
```

And this is because you chose to model all the ghosts in one class instead of having a class `Ghost` and then have 4 instance of it somewhere

**Comment by Alex-Cosma** [comment]
And well, this leads me to another requirement.
I'd like to you make the ghosts "smart". What I mean by this is that they should always follow and try to reach Pacman in the shortest path available. Fun fun, it almost sounds like a Dijkstra here, right? Well it'll probably end up being 4x Dijkstra, one for each ghost if you chose to implement it this way.
I think it would have been a lot harder to implement this if you were to have kept the current implementation of the `Ghosts` class, as it is.
Of course, this will require additional changes, the ghosts will always have to know the whole map and Pacman's position, but surely you can tinker with things and have it done.
Great work!

**Comment by florin-popa** [comment]
I'm really sorry, but I was gone this week (holiday and stuff) and I couldn't work more on my project. I will try however to work on the given requirement, but I don't think I'll finish today.

**Comment by florin-popa** [comment]
I forgot to ask: any idea why the exported .jar file won't run when I hit NEW GAME and the program goes to the the game state? In eclipse everything works just fine. I tried several things but nothing works. The problem could be that some files disappear when the export happens, but I opened the .jar file with WinZip and everything seems to be at it's place.

**Comment by Alex-Cosma** [comment]
Hm, from the top of my head, I don't know. I'll try it myself tomorrow, see what I find out!

**Pull request merged**
