### PR TITLE
Assignment 2.1

### PR DESCRIPTION
**Pull request by mariahada**
I still have to implement an AI so I haven't touched the twists 2 and 5.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
First of all, please move the `checkIfGameOver` method into another class, it shouldn't stay in the activity.

**Comment by Alex-Cosma** [comment]
Thi is not something which may at first look intuitive, but it will help your OOP design.


Now our buttons can be isolated into a separate class and all the "btnClick" functionality could be hidden there. For example, you could create a

```
public class TicTacToeButton extends Button {

    // at least 1 constructor with a Context parameter is needed, you can delete it and see AndroidStudio suggestion
    public TicTacToeButton(Context context) {
        super(context);
    }

}
```

and in the `activity_main.xml` instead of:
```
<Button > ... </Button>
```
 you will have:
```
<com.example.maria.TicTacToeButton> ... </com.example.maria.TicTacToeButton>
```

and in `MainActivity` you will declare the buttons with:
```
 TicTacToeButton[] theButtons;
...
```

In the `TicTacToeButton` class you will be able to write any method including one that can decide what to print on it, or reset it, enable it etc etc. That's how you define a custom view for your application. I would strongly advise moving much of your button-handling code from `MainActivity` into this new custom view class. (yes, you will need a reference to some variables, but you can either cast the `Context` parameter to `MainActivity` or you can pass the references as parameters to your methods)

**Comment by Alex-Cosma** [comment]
Why would you have 2 classes, `Player 1` and `Player 2`, where everything that is different is basically a String. "X" or "O"
Please reconsider this! Really, really bad practice.

**Comment by Alex-Cosma** [comment]
So let's see how your code looks after these changes

**Comment by mariahada** [comment]
I think you've merged this by mistake. Or maybe you thought I've given up on it. Either way, I know I still have to change some things. And I will do it soon I hope

**Comment by Alex-Cosma** [comment]
Ooh I did merge it by mistake! Snap. I merged 2 or 3 by mistake -.- 
I did not think you've given up on it!! :smile:

**Pull request merged**
