### PR TITLE
BlackJack v1.0

### PR DESCRIPTION
**Pull request by BologaMarius**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Great work on the class design and code!

There's one thing I would really really want you to change. You used this:

```
	private static final String IMAGE_DIR = "C:/Users/Bolo/JavaSummer/BlackJack/src/images";
```

And the reason for this was that you placed your images in a `source` package. You should never do that. They belong in a `res` or `resources` folder outside the source packages but inside the project folder, like this:

`C:/Users/Bolo/JavaSummer/BlackJack/res/`

This way, you will be able to load the images without specifying an absolute path as they will be relative to the project folder, not the concrete file system path. Please make this change and make sure the images are loaded correctly and then push back to git. Else, I'll have to manually edit the images location each time I want to check out your application

**Comment by Alex-Cosma** [comment]
However there is not much 'critic' I can throw upon your code. It looks really good and clean!

**Comment by BologaMarius** [comment]
I will do that! What improvments can be done?

**Comment by BologaMarius** [comment]
Merry Christmas and Happy Holidays!

**Comment by Alex-Cosma** [comment]
Thank you! Merry Christmas to you as well :blush: 

I don't see anything you should change yet, however, come up with some new functionality which to add upon your current implementation. Maybe something like a login and a score keeping mechanism?

**Comment by BologaMarius** [comment]
Thank you! 
Done the login and score keeping mechanism, and I've also implemented sort of a betting system..
Any advice or comments are useful!
And you will need this: username:alex and password:1234

**Comment by Alex-Cosma** [comment]
That's all I have to say. Do the UML and you'll be done!

**Comment by BologaMarius** [comment]
Done the changes and also the UML!

**Pull request merged**
