### PR TITLE
chess project

### PR DESCRIPTION
**Pull request by Ranapop**
Here is what I've done for the chess project so far. 
First of all, I'm sorry that I'm sending you code so near to Christmas, I understand there are other things you'd rather do.
But I have quite a lot of questions, and I didn't ask earlier cause I was ashamed of how little I've done. Anyway, here are my questions:
1.Are the classes Board and Cell well constructed? I am not sure if some methods should be there, I think I commented besides them.
2.Should I take into consideration moves like castling and en passant?
3. Do I have to rotate the board when the player is changed?
4. Do I need a class Player?
5. As you will see, in the Piece class I have a method that returns all the possible moves of a piece. As for now, I only implemented it for the knight. Should I proceed with the other implementations or should I replace it with a canMove(Position a, Position b) method?
6.Overall, did I design it well? I spent about two weeks designing classes and writing almost no code at all, but I did wrote a lot in a hurry these past days cause I wanted to have something concrete to show you. 
Well, I think that is all for now. If you can spare some time, please look over it.
And, of course, merry christmas!!!

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
First off, I think it's one of the best designed projects I've seen so far, and to think that I didn't even look at it before! :relaxed: Good work

1. Yes, they're just fine.
- you could however simplify two ifs in the board class:
```
if(piece==null){
            return false;
        }else{
            return true;
        }
```

is equivalent for example to

```
return piece != null;
```

but that's not such a big deal.

2. Hm, well, I'm tempted to say yes, but first you should focus on finishing the basic functionality

3. No, the other player can simply rotate the phone/tablet.

4. Not yet, no, however if you'll ever want to expand the project by offering some sort of `login` functionality, you might, yes.

5. The method should stay as it is because it's beautifully written and here's why:
- In the `Knight` class, I see you have an `offset` matrix indicating all the possible directions in which a piece can move. Basically, each piece will have one of these matrices (careful about the queen though, she'll have quite a large one). 
- now the thing which I like the most (though I might be wrong) is that .. this is the only thing that should differ from piece to piece in this method. I think that the `offset` matrix is the only thing that needs to change in the `getPossiblePositions` method which leads me to the next point
- Again, I might be wrong but if what I said above is true, then you can pull up this method in the superclass (`Piece`) and have something like this:
```
    public ArrayList<Position> getPossiblePositions(Board board) {
         //should I have a method like this?
        //or  would it be better to just have a cand move method that takes 2 positions as parameters(src,dest)?

        ArrayList<Position> possiblePositions = new ArrayList<Position>();

        int [][] offset = getOffset();

        for(int i=0;i<offset.length;i++){
            Position possiblePosition = new Position(position.getX()+offset[i][0],position.getY()+offset[i][1]);
            if(!board.exceedsBoard(possiblePosition)){
                if(board.isPositionOccupied(possiblePosition)){
                    Piece attackedPiece = board.getCellAtPosition(possiblePosition).getPiece();
                    if(this.colour!=attackedPiece.colour){
                        possiblePositions.add(possiblePosition);
                    }
                }else{
                    possiblePositions.add(possiblePosition);
                }
            }
        }

        return possiblePositions;
    }
```

Where `the getOffset()` method is overriden in the subclasses and returns a specific offset matrix for each piece. What do you think? Will this work?

6. The time spent on the class design truly paid off.

**Comment by Alex-Cosma** [comment]
In your `BoardGui` class, you have the following statement:

```
            gridLayout.addView(buttons[i], 50, 50);
```

I've put the project on my phone and the result of using this statement is [this](http://s4.postimg.org/51ky3x2od/Screenshot_20151224_113115.png)

But the result of using

```
            gridLayout.addView(buttons[i], 125, 125);
```

Is [this](http://s9.postimg.org/q2l65h0jj/Screenshot_20151224_113200.png)

You will have to work on somehow dynamically setting this size as to fit larger resolution screens as well.

**Comment by Alex-Cosma** [comment]
Also, when I tried to actually move the `knight` from one place to another, the app crashed, so you have some work to do in that direction as well. 

Anyway, great work and keep it up. Let me know when you have some more code for me to look at.

**Comment by Alex-Cosma** [comment]
And a very merry Christmas to you, as well!

**Comment by Ranapop** [comment]
I really appreciate your review :D and I will do my best in solving what you pointed out. And thank you!

**Comment by Alex-Cosma** [comment]
Well, I get a weird error when trying to run the game.
```
java.lang.OutOfMemoryError: Failed to allocate ... byte allocation with free ... bytes and 10MB until OOM
```
And Google says [this](https://www.google.com/search?q=java.lang.OutOfMemoryError%3A+Failed+to+allocate+a+12160812+byte+allocation+with+11032368+free+bytes+and+10MB+until+OOM&oq=java.lang.OutOfMemoryError%3A+Failed+to+allocate+a+12160812+byte+allocation+with+11032368+free+bytes+and+10MB+until+OOM&aqs=chrome..69i57.278j0j7&sourceid=chrome&es_sm=122&ie=UTF-8#q=java.lang.OutOfMemoryError:+Failed+to+allocate+a+byte+allocation+with++free+bytes+and+10MB+until+OOM)
Do you get it as well?
If not, then just go through and do the UML and you'll show-off the project next week. I have no more comments on it

**Comment by Ranapop** [comment]
I don't think i get that error. But there's a strange thing. I connected my phone through usb to simulate the app directly on a real device. And while it was still connected the app crashed. I disconnected it and tried the app. It was just fine(i mean, for what it's doing now). And i know the behavior of the pieces is good because i decided to move the project in java and i replaced the view part with reading and writing from standard input. And, at least on the board, the pieces move just fine. But I still have some game logic left to do, like when it's check and checkmate, so I can't proceed to the uml just yet. The app its kinda useless without that part =)) And I will try to run it on some other device as well, to see what other problems I may encounter :D (I just have to steal some phones, i mean borrow)

**Comment by Alex-Cosma** [comment]
You don't have to send it, you can just show up with it on the day of the presentation.
Great work! mergin.

**Comment by Ranapop** [comment]
well... there are some fields i turned private but i guess it's not that big of a deal... and the diagram is still in progress, i really hope it will turn out well, im just afraid it will be impossible to read the method names as the'll be quite small when i turn it into an image :? so... will I have to print it out? :?

**Comment by Alex-Cosma** [comment]
No, you can have it on the pc only

**Pull request merged**
