### PR TITLE
Nine Men's Morris - Project

### PR DESCRIPTION
**Pull request by BiancaTosa**
I have modified the project as you suggested. Is it ok ?

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Things look a lot cleaner, but there are some more things which can be done

**Comment by Alex-Cosma** [comment]
Good! Now only a few aesthetic things left.
- move all your images to a `res` folder in the root of the project. The source folder should never contain anything besides actual Java code.
- for someone playing Nine Men's Morris for the first time, it might be slightly difficult to follow who's turn it is, what he/she has to do and so on. I was thinking about implementing a bar on top of the game board, like, I don't know, 50 pixels in height? in which you should simple write stuff like `black turn to place` or `red turn to remove black piece` etc. etc. based on who's turn it is to do what.

That would be all. Once you've completed this, you're all set and done!

**Comment by BiancaTosa** [comment]
Can I start working on the UML ?

**Comment by Alex-Cosma** [comment]
Yup

**Comment by Alex-Cosma** [comment]
You're done. Happy new year!

**Pull request merged**
