### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by andinicolescu**
Asking for the final confirmation on the whole project. Looking forward to making this the perfect TicTacToe there is!

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Also, I have told you before:

One more thing which I forgot to tell you about.
The audio/visual assets should never be placed in `source` packages. Rather, you can place them in folders outside your source packages. In the source packages you should only have source files.
This way, you will not be needed to hard-code them like this: `C:/Users/Andi/workspace/ProjectT/src/Sounds/t1.wav` as you will be able to use a relative path. :smile:

**Comment by andinicolescu** [comment]
I'll make the changes. About the sounds and icons. They are not in the source folder. Check again. Students/30422/Nicolescu D. Alexandru/ProjectT/Sounds/t1.wav. I've created sounds and icons in the project file.

**Comment by Alex-Cosma** [comment]
But then you did not delete them from the source packages

**Comment by andinicolescu** [comment]
Did everything you said. Lots of changes in the GUI-GameManagement classes only one "pvp" variable now and only sending playerLastMove, removed difficulty. Difficulty is only sent when selecting which class to use.

**Comment by andinicolescu** [comment]
Solved everything you said :muscle:

**Comment by Alex-Cosma** [comment]
There is one thing that bothers me - a lot.

**Comment by Alex-Cosma** [comment]
In the `Player` class you have this:

```
	private static volatile Player[] players = new Player[10];
```

What in the world is this supposed to be?

and this:

```
	public static synchronized Player[] getInstance() {
		if (players[0] == null) {
			for (int i = 0; i < 10; i++) {
				players[i] = new Player();
			}
		}

		return players;
	}
```

Why can you have only 10 players? Shouldn't the players just be read from the file? Why do you allocate them here, in this class?
You should simply retrieve all of them from the file! And you are doing that, in the `AccountRepository` class, the `manageData()` method, here:

```
players = (Player[]) in.readObject();
```

Why then do you have the other thing, there?

**Comment by andinicolescu** [comment]
First of all, I'll delete the Singleton from player. I don't need it, I restructered the program and I don't need it. So 
private Player players[] = Player.getInstance();
turns into
private Player players[] = new Player[10];
this is when I define players[] into AccountRepository. But you're saying I don't need to mention the length of the array when I define it?

**Comment by andinicolescu** [comment]
This seems right to me. Why not? Because you only need to take the array already made from the .ser file? How do you do that if so? I am creating an array and putting the data into it now, right?

**Comment by andinicolescu** [comment]
What about creating a global MAX_NR_OF_ACCOUNTS=10 in this case  and display a message when reaching the limit

**Comment by Alex-Cosma** [comment]
you can have

```
Player players[];
```
as class attribute and 

```
players = (Player[]) in.readObject();
```

Done.

**Comment by andinicolescu** [comment]
I think there's a problem with the pull request label :smiley:

**Comment by Alex-Cosma** [comment]
I'm sorry Mr. Nicolescu, but I see way too much potential in you to simply let you off now.

**Comment by Alex-Cosma** [comment]
New requirement:

- add a new entry to the `choice` menu: *computer vs. computer* and make sure that you can select the difficulties for both computers.
- have a match created between the two computers and make it such that once every `x` seconds (parametrise this) one of them will make a move. 
- hint: use a [Timer](http://www.tutorialspoint.com/java/util/timer_schedule_period.htm)
- try not to clog your current code up too much

Yes, this is a test to see how well you've designed your code and how easy it is to expand it.

**Comment by Alex-Cosma** [comment]
Oh and...

The label stays.

**Comment by andinicolescu** [comment]
Just finished Easy and Normal difficulty for Computer vs Computer. Everything works perfectly, added the timer, the menu option, no bugs at all. I'll continue tomorrow with MinMax vs MinMax. Not that hard to expand. Just added new methods like makeCVCMove(playerLastMove)

**Comment by andinicolescu** [comment]
Computers are playing both at the same difficulty. You want each to have a certain difficulty?

**Comment by andinicolescu** [comment]
Same difficulty at both computer players please? Works to good and looks to nice to edit

**Comment by Alex-Cosma** [comment]
Fine, you can leave it like this

**Comment by andinicolescu** [comment]
I needed to:
-cover the case of being a total of 9 moves in EasyAI and NormalAI instead of 5 as it was before
-implement the CVC mode in GUI
-switch players so that MiniMax will try to make both of them win

**Comment by Alex-Cosma** [comment]
Not bad. It's actually quite alright. Don't forget about the UML diagram btw.

I think we're done here, for now.. What do you think, are we done?

**Comment by andinicolescu** [comment]
I thought this moment will come, but I didn't expect it now. What a wonderful Christmas present!
I'll upload the UML soon. Thanks a lot for everything. Really helped!

**Comment by Alex-Cosma** [comment]
What can I say...

Me > Santa.

**Pull request merged**
