### PR TITLE
Chess help #4

### PR DESCRIPTION
**Pull request by vblana**
I know i made a mess of the static methods and attributes but i will sort it out later.
My problem is with the kingSafety method.
Theoretically it should work and i have no idea why it doesn't.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Oh never mind, you created a new pull request, ok

**Comment by Alex-Cosma** [comment]
I don't think you committed all your code. I don't see the class `PieceManipulation` anywhere

**Comment by Alex-Cosma** [comment]
Nevermind, it's a package, but it should be called `Pieces` not `PieceManipulation`

**Comment by Alex-Cosma** [comment]
Or is it a class? what the hell is going on :laughing: Please commit compilable code!

**Comment by vblana** [comment]
How do i recommit without creating a new pull request?

**Comment by Alex-Cosma** [comment]
you can simply commit + push. the new commits will appear on this same pull request

**Comment by vblana** [comment]
The class movement checks if a movement is possible and makes a move.
How should i change the name?

**Comment by vblana** [comment]
The coordinates of the king is just and idea and probably a bad one.I'll just delete those.

**Comment by vblana** [comment]
The move is encoded,yes.
When the user clicks on a square and drags a piece, the action is encoded to the string move as follows: x,y coordinates of the clicked square + x,y coordinates of the released square.
To me it seems like a good solution.

**Comment by vblana** [comment]
And about all those statics.
Would it be better to instantiate 4 different classes and pass them around as parameters everywhere?

**Comment by Alex-Cosma** [comment]
Then you should have MovementManager and the methods for checking and moving should be different. One method should check, the other should move.

**Comment by Alex-Cosma** [comment]
It isn't a good solution, why encode when you can create a class called `Movement` which has fields like: `sourceX`, `sourceY`, `destX`, `destY`, or even
```
public class Movement {
    public Point source;
    public point destination;
    // + everything else you need
}
```

Then you wouldn't be needed to encode and decode strings every time.

**Comment by Alex-Cosma** [comment]
If you truly have to pass references around and there is no other way to have a lower coupling in your architecture, then yes, passing instances would be better.

**Comment by vblana** [comment]
There.
No more static.
Please tell me if there are any more design flaws before i get to work on castle and king safety.

**Comment by vblana** [comment]
Also changed the encoding of the move as you suggested.
It is indeed much more elegant this way.
the white/black king x,y will be edited out once i figure out king safety and most likely replaced by attributes of the king piece.

**Comment by Alex-Cosma** [comment]
Great work, but I have a question:

What does the `public String possibleMove(int row, int column, Piece chessBoard[][], boolean checkKingSafety, Controller controller)` return?

**Comment by vblana** [comment]
Well, it returns the move encoded into a string.
I haven't found another way of checking if the move the player made is in the list of possible moves without encoding.

**Comment by Alex-Cosma** [comment]
But you now have a `Movement` class. Why not return a list of such objects?

**Comment by vblana** [comment]
I see.
Any other problems?

**Comment by Alex-Cosma** [comment]
Not yet, no

**Comment by vblana** [comment]
I have a small problem in checkValidMove where the list contains the correct possible moves, but it cannot identify the move the player made with the one in the list with list.contains(move).

**Comment by Alex-Cosma** [comment]
I think you may have to override your `equals` method from the `Movement` type. Google this, you'll learn a lot on how the `contains ` method works!

**Comment by vblana** [comment]
Well, i kinda solved it.
I am comparing using the convertToString method which is needed somewhere else anyway.
I tried overriding and creating my own methods for comparing but they are not working.

**Comment by vblana** [comment]
Nevermind the last comment,i figured out what was wrong.
I also implemented the kingsafety and castle methods.
Basically, the functionality part is done.
What is left to implement is a message when a king is in check and one when there is a checkmate.
Should I implement something else?

**Comment by Alex-Cosma** [comment]
Great! Much better.
- I think castling doesn't really work correctly yet - if I do a castle move, instead of switching the king with the knight for example, the king is placed in the right position but the knight disappears.
- also, regarding castling. I would make these verifications:
```
if (move.source.x == 7 && move.source.y == 4 && move.destination.x == 7
				&& move.destination.y == 2
				&& chessBoard[7][4].getType() == Pieces.KING)
...
```

into something like this:

```
if (castleKnightMove(move, chessBoard)) {
...
```

And then have all these checks done separately in their own methods. The reason is that it is difficult to understand what this code does actually, so, maybe hiding its innards in different methods will clear things up.


- one last thing, once a piece has been selected and is to be moved, I would very much like you to highlight all the squares onto which you can place that piece. I don't think that'll be too difficult to do as you already know all of a piece's possible moves.

That would be all!

**Comment by vblana** [comment]
Well, first of all the castle can only be made with the rook.
I tested most of the cases(all castle moves(4 of them),castle when a specific square is in check etc and it works).

Merging that condition into a method is quite doable.

However, the highlighting part is not difficult because i don't know all the positions, but because the graphics can only be accessed from within paintComponent

**Comment by vblana** [comment]
Done.

**Comment by Alex-Cosma** [comment]
1 more thing and you can start working on the UML diagram:
```

**Comment by Alex-Cosma** [comment]
Also, you can add
```
f.setLocationRelativeTo(null);
```
in `ChessFrame` so it will be centered :relaxed:

**Comment by Alex-Cosma** [comment]
So, create the UML and you're done!

**Pull request merged**
