### PR TITLE
Demos

### PR DESCRIPTION
**Pull request by AlexaGh**
I only have some demos of the "game". Firstly I worked in eclipse, to see how I would manage my classes and then I worked in AndroidStudio (not much, tho' -just managed to flip s(one) cards for now-). 
So, this is not the project, more likely some demos to see if I'm on the right track or not -if one can tell from that bit-

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I think you can safely go ahead and try to implement it on Android, I don't think you'll have any difficulties. Great, great work!

**Comment by AlexaGh** [comment]
Another Demo in Android, for multiple cards flipping. 
If I want to use a photo with high resolution in the background, it breaks because "the process may be doing too many things". Until I will figure how to implement a thread or something, I will leave it as simple as that and continue with my implementation.

**Comment by Alex-Cosma** [comment]
You should definitely use an [AsyncTask](http://stackoverflow.com/questions/9671546/asynctask-android-example) for that!

**Comment by Alex-Cosma** [comment]
That's about it. I think you should implement a timer for the cards, it would still be more elegant but the code looks clean enough, though the project is rather simple.

Using shared preferences, you might add a `highscore` (per difficulty) system.

**Comment by AlexaGh** [comment]
Actually there's also another difference, the images, namely, the names of the drawables, which I "handled" by using a String parameter in the setCards method, but I'll also leave the setCards method to the Easy/Hard/Medium implementations.

**Pull request merged**
