### PR TITLE
Tic Tac Toe - Twist 1,3,4

### PR DESCRIPTION
**Pull request by kovacsgellert**
Everything working as expected. However I am not sure how I should have
structured the code to be more readable, easier to understand and more
in line with the OOP paradigm. I would like to ask for some advice.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
So, first off, using such a `boardMatrix` is a good idea, so that stays.

**Comment by Alex-Cosma** [comment]
Now our buttons can be isolated into a separate class and all the "btnClick" functionality could be hidden there. For example, you could create a

```
public class TicTacToeButton extends Button {

    // at least 1 constructor with a Context parameter is needed, you can delete it and see AndroidStudio suggestion
    public TicTacToeButton(Context context) {
        super(context);
    }

}
```

and in the `activity_main.xml` instead of:
```
<Button > ... </Button>
```
 you will have:
```
<com.gellert.tictactoe.TicTacToeButton> ... </com.gellert.tictactoe.TicTacToeButton>
```

and in `TicTacToeMainActivity` you will declare the buttons with:
```
TicTacToeButton btn00;
...
```

In the `TicTacToeButton` class you will be able to write any method including one that can decide what to print on it, or reset it, enable it etc etc. That's how you define a custom view for your application. I would strongly advise moving much of your button-handling code from `TicTacToeMainActivity` into this new custom view class. (yes, you will need a reference to some variables, but you can either cast the `Context` parameter to `TicTacToeMainActivity` or you can pass the references as parameters to your methods)

**Comment by Alex-Cosma** [comment]
Besides this, there are a few things which are rather 'ugly' code wise.

1) why are the variables `boardMatrix`, `scoreX` and `scoreO` public AND static? they can actually just be private! yes, you need them in the `saveScore` class but why not just pass them as parameters?

2)

**Comment by Alex-Cosma** [comment]
Let's see how your code looks after this refactoring!

**Comment by kovacsgellert** [comment]
I don't understand how to move my generic button click method (btnClick) from the MainActivity to my new TicTacToeButton class. I would like to ask for further explanation. And after I move it how should I use it when I create de button click listeners in the MainActivity?

**Comment by Alex-Cosma** [comment]
What if you'd assign two indices for each button? A row and column index for the backing matrix? Would that maybe clear up things for you? 
Of course, the listener will not stay 100% the same, but do you think you can figure it out from here/

**Comment by kovacsgellert** [comment]
I've tried to do the refactoring you suggested, but I ended up with a
different result then the proposed one. I hope the code is not as ugly
as it was.

Unfortunately, it does not work, as I get a NullPointer error at line 58
in the main activity. After debugging I can confirm that the lines 46-54
have no effect whatsoever, the buttonMatrix contains null values after
the assignments so when the app tries to call
buttonMatrix[i][j].resetContent(); it obviously crashes.

The problem is I have no idea why the assignments don't work.

And as a second thought the onClickListener still seems ugly, but I had
no better idea.

**Comment by kovacsgellert** [comment]
Regarding the problem I had: EPIC FACEPALM... Thank you.
I will try to implement the state machine as well, it seems simple.

**Comment by kovacsgellert** [comment]
Finally everything is working again. I also moved the score keeping part to the GameState class, as scores are also related to it.

**Comment by Alex-Cosma** [comment]
Ok, great. So already things are looking better. Now, about this click listener, I think you can now even more easily move it into the `TicTacToeButton` class, don't you think? Implement the OnClickListener interface in the `TicTacToeButton` class and copy the code from the Activity. You'll be missing the `buttonMatrix` object, however, you can fetch it by creating a simple getter for it in the activity, and casting the `context` in each constructor to a `TicTacToeMainActivity` (or creating a setter for this activity in the `TicTacToeButton` class, your choice).
Do you think you can follow things up from here?

**Comment by kovacsgellert** [comment]
I don't really get the part about casting the context, but I think it will be the easiest to ask you in person on Wednesday so that you don't waste your time trying to explain it to me in writing. Now I will start working on the Zoowsome part of this week's assignment. I hope it's OK this way. :)

**Comment by Alex-Cosma** [comment]
So, it's quite simple, don't need to wait that long. Notice the `context` parameter which is passed into all the constructors of your button? That context is actually the activity in which the button is in, so, for example, you can write:

```
TicTacToeActivity act = (TicTacToeActivity) context;
```

**Comment by kovacsgellert** [comment]
My problem was I did not understand how I could use this context parameter from the contructors in the new onClick method. It turns out it was simple. The app really surprised me, as it is working OK. :)

**Comment by Alex-Cosma** [comment]
There we go! The code looks great now, don't you think? :smiley:

**Comment by kovacsgellert** [comment]
I agree. This line of code still astonishes me:
 buttonMatrix[i][j].setOnClickListener(buttonMatrix[i][j]);

**Comment by Alex-Cosma** [comment]
That line shouldn't be there actually

**Comment by Alex-Cosma** [comment]
However, in the constructors of the button you will have to add: 
`setOnClickListener(this);`

**Pull request merged**
