### PR TITLE
BlackJack Project

### PR DESCRIPTION
**Pull request by goiapaula**
Sorry if it's a bit to late to send you the project, but I had some problems with my laptop and, well yeah :)) , with my project.I hope it works well enough XD.
Merry Christmas and a Happy New Year!!!!

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
When the player busts, I want you to do the exact same thing you're doing when he/she stands.

**Comment by Alex-Cosma** [comment]
Moving further, you should implement an 'account' system - you log in with a certain account which has (at the beginning) a default amount of $. You can then bet a certain amount of $ at the beginning of each game ... you know the rules. 
Play around with something like this -> ps: once a player logged in, you should not ask for its 'name' and please simply give default values to the bots, there is no need to give them specific names as they are bots.

**Comment by goiapaula** [comment]
I have a question regarding the account part..You want me to use databases?? Or how am I supposed to memorize how much money the players has?Sau cu serializare?? Ca sincer nu prea  stiu cum sa fac partea asta..(Scuze ca am dat-o  pe romana dar mi-e mai usor sa intreb asa)
Sau vrei ceva de genu  ...cand dai start si dai " log in" ai o suma initiala si pana nu iesi de tot din joc sa poti paria cat timp ai bani.

**Comment by Alex-Cosma** [comment]
Ar trebui să serializezi/deserealizezi un array list de `Account`. Google how to do it. Nu trebuie cu baze de date.

**Comment by Alex-Cosma** [comment]
Yes! Awesome. I have nothing to add here.
You can of course improve on the visual side of things, but that is not really a concern of mine. Great work and I hope you enjoyed it.

**Pull request merged**
