### PR TITLE
Tetris unfinished

### PR DESCRIPTION
**Pull request by LaviniaSara**
The pieces can now move using the arrow keys. I still need to implement the rotate method.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Thank you for your wishes and happy holidays to you as well!

**Comment by Alex-Cosma** [comment]
Other than these things, your code looks pretty neat, however there are some further development which you'll have to do:
- Whenever I reach the bottom with my first piece, another one does not show up. 
- You should make your frame/squares bigger
- You should remove the borders of the squares unless they contain a shape
- You should keep the score somewhere

Great work so far and good luck!

**Comment by LaviniaSara** [comment]
Thanks!
New pieces are generated and the pieces get placed on the board.
I have some trouble with rotating the pieces.
I am done with the logic of rotating the pieces (rotatePiece method in
class Shape). I am not sure how to make the connection between this
method and the UI.
Also, I have made some of the changes you wanted me to make.

**Comment by Alex-Cosma** [comment]
in `GamePanel`, `	public static Shape shape;` should just be `private Shape shape;`. The way you wrote it is pretty much procedural. 
Conceptualize the problem: every `GamePanel` should have its own falling shape, *not* every `GamePanel` has the same shape object shared amongst them

**Comment by Alex-Cosma** [comment]
The problem with your rotate method is an `index out of bound` exception - debug it.

**Comment by Alex-Cosma** [comment]
Yey, great! Here are a few suggestions:
- I think that if you make your board all black or all white, it would be slightly better looking.
- Also please format your code using `Ctrl + Shift + F`
- Delete any unnecessary code / commented code
- This method for example is very ... weird
```
	public void checkIfMoveWasLegal(boolean[][] pieceMatrix){
		for(int i = 0; i < shape.getMatrixRows(); i++){
			System.out.println("i = " + i);
			for(int j = 0; j < (shape.getMatrixCols()); j++){
						if(pieceMatrix[i][j]){
							if(((j + shape.getPieceCol()) > (BOARD_COLS - 1)) || ((j + shape.getPieceCol()) < 0) ||
							((i + shape.getPieceRow()) > (BOARD_ROWS - 1)) || //check for bounds
							((squares[i + shape.getPieceRow()][j + shape.getPieceCol()].getBackground()) != 
							Color.LIGHT_GRAY)){                                //check for other pieces already there
								shape.setPieceRow(shape.getPrevPieceRow());
								shape.setPieceCol(shape.getPrevPieceCol());
								shape.setMatrixRows(shape.getPrevMatrixRows());
								shape.setMatrixCols(shape.getPrevMatrixCols());
								shape.setLegal(false);
								
							}
							
							else{
								shape.setLegal(true);
							}
							
							
						}
					}
			 }
		}
```

Take a look at that huge `if` statement in the middle. Is it really necessary? I mean, why should the colour matter? Shouldn't verifications on the `pieceMatrix` be enough?

Overall, good work!

**Pull request merged**
