### PR TITLE
Breakout Project

### PR DESCRIPTION
**Pull request by negreamihneavlad**

### CODE REVIEW

**Comment by negreavlad95** [comment]
you should watch only over the last commit, named "This is my project"....the other ones are failed uploads

**Comment by negreavlad95** [comment]
that static reference brick its not needed, ok, i have to clean up the code a little bit and to get rid of those statics

**Comment by Alex-Cosma** [comment]
:

**Comment by negreavlad95** [comment]
i didn't manage to call "createMario"  without making it static, and then i had to make those brick[][] and flag[][] static.

"I don't understand why you keep a static reference of this class inside the class itself"

i did that to use it in different classes but i can get rid of it and create it separately for each class (if it is needed)

**Comment by Alex-Cosma** [comment]
Well the thing is, you should pass references around, not use static ones. For example, instead of having this:

```
    public class A {
        public static A objA;

        public static void methodA() {
            // ...
        }
    }

    public class B {
        public void method() {
            A.a.methodA();
        }
    }

```

You should maybe have this:

```
    public class A {
        public void methodA() {
            // ...
        }
    }

    public class B {
        public void method(A a) {
            a.methodA();
        }
    }

```

Or this:


```
    public class A {
        public void methodA() {
            // ...
        }
    }

    public class B {
        private A a;

        public B(A a) {
            this.a = a;
        }

        public void method() {
            a.methodA();
        }
    }

```

See, there are many ways in which you can use references and not the static keyword to access things from different classes, but the main idea is that you should always create and pass around object references, else, your code will simply end up being procedural, not objectual

**Comment by negreavlad95** [comment]
i tried to do for Mario like i did for Ball or Pedall, creating a reference in Game class, and then calling the method createMario, but its not working, this is how i tried firstly, but it didn't worked, or i wasn't able to do so, and i've changed it to static

**Comment by Alex-Cosma** [comment]
Don't give up! :relaxed:

**Comment by negreavlad95** [comment]
i've created in Game 
public Mario mario;

and called in render method

mario.createMario(g,ball);

and change createMario from static only to public void...

this thing should work if you take it by the book? no?

**Comment by Alex-Cosma** [comment]
Google is your friend.

**Comment by Alex-Cosma** [comment]
But I don't fully understand what should 'work by the book'.

**Comment by negreavlad95** [comment]
Could you tell me if its ok?

**Comment by Alex-Cosma** [comment]
Much better! I'll take a more in depth look tomorrow

**Comment by Alex-Cosma** [comment]
So, I've just looked at it again and it's much better, don't you think?
Do the UML diagram and you're done

**Comment by negreavlad95** [comment]
I have to come in re-examination session to present you the project?Or is fine?

**Comment by Alex-Cosma** [comment]
Not sure about that yet, but I'll keep you posted

**Pull request merged**
