### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by mariahada**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
If you don't have any questions, feel free to move on to the next tutorial

**Comment by mariahada** [comment]
I think everything's clear. So far...

**Comment by Alex-Cosma** [comment]
“Fear is the path to the dark side. Fear leads to anger. Angers leads to hate. Hate leads to suffering. I sense  much fear in you.” - Yoda

Ah.. Being a geek

**Comment by mariahada** [comment]
"I know"

**Pull request merged**
