### PR TITLE
This is only an initial version of Snake.

### PR DESCRIPTION
**Pull request by uivlis**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
First off, you have 3 classes in the `(default package)` which makes the project uncompilable (at least on my machine) - please move them in a separate 'named' package

**Comment by Alex-Cosma** [comment]
You have 2 classes with the exact same name: `RenderPanel` - please rename at least one of them so it will remove some of the confusion around what each one of them does

**Comment by Alex-Cosma** [comment]
Good package placement, but still needs work on breaking down the classes and giving each one the responsibility it needs.

**Comment by Alex-Cosma** [comment]
Yes! Awesome, there are only a few things I would like you to change and then you can start creating your UML and be completely done with it.
- rename your `SnakeKey` class to `SnakeController` 
- create a method inside your `GameManagement` class called `getGameFrame()` which will call `return renderPanel.getFrame();` (yes, that would mean creating such a method in your `RenderPanel` class which simply returns the `JFrame jframe;` 
- change `JFrame jframe;` in `RenderPanel` to `private JFrame jframe;`
- in `SnakeController`, instead of `RenderPanel.jframe.dispose();` you will have `game.getGameFrame().dispose();
- also, all static references to this attribute will disappear
- move `RenderPanel` class to `views` package as it is actually a view

**Comment by Alex-Cosma** [comment]
And you're done! Congrats. Don't forget about the UML diagram but you can bring that at the presentation as well, no need to upload it.

**Comment by Alex-Cosma** [comment]
So what do you think? Do you like how your code ended up looking?

**Comment by uivlis** [comment]
Indeed, in the end, it looks much more like OOP should look like. Thanks for your help.

**Pull request merged**
