### PR TITLE
fluffy

### PR DESCRIPTION
**Pull request by todericidan**
Simplified version with less classes

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I like the fact that you created a `MyLabel` class and added an `x` and `y` coordinates, however.
- the `JLabel` class already has a `text` attribute. Are you sure you need another one?
- the name.. `MyLabel`.. so bad. so bad.

**Comment by Alex-Cosma** [comment]
In your `GameUI` class. Why is everything static?

**Comment by Alex-Cosma** [comment]
Surely, the `keepYellowClues` method helps, but there are so many hardcoded coordinates there! is there no way around that?

**Comment by Alex-Cosma** [comment]
A general hint: too much of.. everything happens in the `GameUI` class. Maybe break it or refactor it?
Great work otherwise.

**Comment by todericidan** [comment]
in the last version I uploaded, I figured out my mistakes except for the refactoring part. I had problems trying to refactor, not only at the lab but also at home, there are some null pointer errors that I don't know how to fix .On the other hand, there are no more static methods(those came when I had  name fluffy static and also the method that initializes fluffy static), also I dropped the MyLabel class.I had a problem while implementing and I thought that a new Jlabel type class would help,but I found an easier solution and forgot to delete the new class.

**Comment by todericidan** [comment]
I forgot to mention that we worked on this assignment (Blana Vlad,Calin Timbus and myself)

**Comment by todericidan** [comment]
So that you know,since it's the same project there is no need for them to upload it

**Comment by Alex-Cosma** [comment]
Much better, keep it up!

**Comment by todericidan** [comment]
we refactored Fluffy and split GameUI in 3 different classes Game(which is the backend,where there is only the fetching of data and initialization of the 2 matrix and also the positioning of fluffy),GameView(which does all the moving of the fluffy imageIcon) and GameController(which listens to the input controllers and tells GameView what to do)

**Comment by Alex-Cosma** [comment]
I got close to no internet access until tomorrow morning, so I'll look over your work then.

**Comment by Alex-Cosma** [comment]
Merged this, for now.

**Pull request merged**
