### PR TITLE
Chapter 3, Assignment 3 Zoowsome

### PR DESCRIPTION
**Pull request by nagyhanna**

### CODE REVIEW

**Comment by nagyhanna** [comment]
Hy there,
I deleted the zoo part 1 folder, and I committed&pushed  the updated zoowsome part 2 folder,
but I cannot make a pull request. ..
...

**Comment by Alex-Cosma** [comment]
You don't need to make a new pull request! Pretty please open this one because it was not merged -> your new commits appear here

**Comment by nagyhanna** [comment]
Voilá

**Comment by Alex-Cosma** [comment]
Oh iei, great! I'll look over it tomorrow afternoon :smile:

**Comment by Alex-Cosma** [comment]
I think it's ok, I'm going to merge this to get rid of any future problems

**Pull request merged**
