### PR TITLE
Digital Catalog - DB implementation

### PR DESCRIPTION
**Pull request by kovacsgellert**
I think there will be no need for separate Students and Teachers tables, because al the data from these tables from the 1st version are now present in other tables, so only the Persons table remains which will be connected to all teh other tables through the personID column. I hope it is OK this way.

### CODE REVIEW

**Comment by kovacsgellert** [comment]
I am getting an exception and after hours of browsing the net for a solution I got nowehere. I would like to ask you to look through my code and help me. I committed my code.

My issue is describet here in detail: http://stackoverflow.com/questions/34500257/cursorindexoutofboundsexception-index-1-requested-even-after-using-movetofirst

**Comment by Alex-Cosma** [comment]
Good to see you're actively using StackOverflow! I'll try to debug your code myself now

**Comment by Alex-Cosma** [comment]
Am postat și eu un răspuns dar sincer, nu înțeleg care era problema. Mie îmi merge bine și așa cum e.

Acum primesc eroare aici:

```
    public int getPersonID(String username) {
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor result = db.rawQuery("SELECT personID FROM ACCOUNTS WHERE USERNAME = '" + username + "'", null);
        return result.getInt(0);
    }
```

mai exact, la `result.getInt(0);` dar aici cred că te-ai bucura și tu să ajungi că problema e mai evidentă

**Comment by kovacsgellert** [comment]
Nu stiu de ce dar dupa ce am sters aplicatia veche si am reinstalat versiunea cea mai noua pe telefon, problema a disparut... Interesant. Acum ca am schimbat si partea getPersonID totul functioneaza fara probleme. :smile:

**Comment by Alex-Cosma** [comment]
:+1:

**Comment by kovacsgellert** [comment]
If I understood correctly, students should only be able to check their marks and nothing else, right?

**Comment by Alex-Cosma** [comment]
Yes, that is correct

**Comment by kovacsgellert** [comment]
In the TeacherActivity I left the actionlisteners for the two Spinners in the onCreate() method. I would like to ask if that is ok? Everything works until now, I will just have to add another activity for adding/updating marks for a given student. This will be reachable by clicking on a student!s name from the list.

**Comment by Alex-Cosma** [comment]
Sure, it's fine to leave them there.
For your other question, here's your [answer](http://stackoverflow.com/questions/21881992/when-is-sqliteopenhelper-oncreate-onupgrade-run)

```
SQLiteOpenHelper onCreate() and onUpgrade() callbacks are invoked when the database is actually opened, for example by a call to getWritableDatabase(). The database is not opened when the database helper object itself is created.
```

However, I think it would be good if you'd have a singleton for that object.

**Comment by kovacsgellert** [comment]
I think my project is done. I also tried to create a UML diagram, but the result is a total mess.
Please check my code and tell me if there is need for modifications. Thank you and I wish you a happy new year! :smiley:

**Comment by Alex-Cosma** [comment]
Excellent work! I don't have anything else to add :+1:

**Pull request merged**
