### PR TITLE
Chapter 2.

### PR DESCRIPTION
**Pull request by AlexandruGH**
Greetings!
I think that my root approximation method doesn't work properly all the time.

### CODE REVIEW

**Comment by AlexandruGH** [comment]
Greetings! I made some modifications.

**Comment by AlexandruGH** [comment]
I made some modifications and I tried the bisection method for some simple examples and it worked.

**Comment by Alex-Cosma** [comment]
OK, great! Good work, you can move o

**Comment by AlexandruGH** [comment]
Greetings !I pushed the chapter 3 as well .

**Pull request merged**
