### PR TITLE
OOP Project

### PR DESCRIPTION
**Pull request by popmihai09**
Hello and Happy New Year, Alex! 
My project is almost done, but I don't know how to verify if King is in Check. I hope that everything else is ok.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your code is copied from [here](http://sourceforge.net/p/game-soccer/code-0/HEAD/tree/trunk/).
Invalidating the project.

**Comment by popmihai09** [comment]
I didn't know that the code is copied from there, because I asked a friend to help me to finish my project and it looks like she just copied that project. I know that I have no excuse, I was too lazy to start it earlier, but can I do another project?

**Comment by Alex-Cosma** [comment]
Yeap, you will have to - pe restanțe.

**Comment by popmihai09** [comment]
Can I choose another project? 

Colocviul tot in restante?

**Comment by Alex-Cosma** [comment]
Colocviul și examenul puteți să le dați acum.

Sure you can

**Comment by popmihai09** [comment]
Ok, thank you!

**Pull request merged**
