### PR TITLE
SQLite Zoosome - SQLite integration

### PR DESCRIPTION
**Pull request by alexh95**
Changelog:
- Implemented SQLite support:
    - A table for Animal, every Class (i.e. Mammal), every Species Classes.
    - Can insert animal data into the db by passing an Animal object.
    - Can return an ArrayList with all the animals in the database. It uses a query for every species (all 24). It is the only way to determine which species an animal belongs to because checking if the animal is a bear would require searching its id in the bear_table: There is no way (that I know of) of returning the table name (or some index) given a id that is linked to it, so I did it the other way around: I searched for all bears in the database and added the result to the list.
    - Migrated resources from Constants to Animal and Class classes to establish a direct dependency instead of an indirect one (the Constants class knew things about Animal that Animal didn't know itself). Now Constants references resources form Animals (the dependency I was talking about)
    - Using arrays in Constants, methods that return the field values in a generalized form and generalized constructors all across the board, the usage of Reflection API is lowered, using only getConstructor and newInstance.
    - Constants is a bit more clean now, just a bit.

TODO:
- create a create activity
- create another view for displaying more details when clicking on the listView which will contain an option to edit
- add pics

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Again, awesome job.

**Comment by alexh95** [comment]
I moved the logic from the constructor in the setter where it belonged. Made some changes to table names and also made sure that the main table uses autoincrement. Inserting the data in the inheritance tables still requires extracting the id back from the table.

**Comment by Alex-Cosma** [comment]
Then I've got nothing more to add.

How were android assignments for you? Were they useful? Did they help you get the general look-and-feel of the Android platform? Some feedback would be great!

**Comment by alexh95** [comment]
The assignments were a good introduction to android considering we came from swing and had a somewhat similar view system. I can produce simple apps but I'll still want to experiment with adding view components dynamically, fragments, drawers, some more save state logic at orientation change and eventually a graphics library.

As an update on the project I'll want to implement it with java swing at the moment since it has most of what I want to use and I want to focus on the model and controller. After I get it working nicely I'll consider porting it on android or starting to look into lightweight java game library to upgrade it.

In any case something that got my attention is this https://handmadehero.org/. Making a game in C++(only for some extra features, not OOP) from scratch without any libraries, but I want to experiment some more with SDL and/or LWJGL before attempting to make my own.

**Comment by Alex-Cosma** [comment]
In my experience, games should not be written in Java. Java is a lot slower than C++ and well, it's just not worth it. But, OpenGL is .. kinda the same thing on all platforms so you can learn it on any of them.

Thank you for the feedback and good luck with your project.

**Pull request merged**
