### PR TITLE
Under construction + a bit of a timer issue

### PR DESCRIPTION
**Pull request by vatavului**
Hello!
I hope you had a great Christmas/Star Wars episode VII experience. 
This is not a final version of the project. I am aware of the fact that the code is a bit messy and I'm planning to do a little cleaning very soon (I know, It should look clean as I am writing it but I'm still developing on that), but I have this timer issue right now. 

I restart the timer when an answer is given (in GameFrame), it looks like it's restarting but the old countdown is still happening. I'm sure I'm not getting something right. How should I fix it?

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Actually, your code looks pretty nice, not much to add there
But unfortunately I won't go into bugfixing your timer problem. :disappointed: You'll have to figure it on your own.
However, you will have to add some sort of 'high score' mechanism or 'leader board' or something similar to you application. For now, it's a bit too .. lightweight.

Think about a simple login, with just a username and once you selected a user/player, either he/she has a score if he/she already played, or starts off from 0. Once he finishes a game, you save his/her score to a file along with his/her name. Make sure to almost fully separate the logic of doing this from the game logic. You should have something like a `Player` class with a `username` and `score` and a `PlayerService` or however you want to call it for saving/retrieving the scores for players.

Good luck!

**Comment by vatavului** [comment]
Thanks for the suggestion, Alex. I also thought that it needs more weight, but instead of that I thought (and I am almost done with) of adding a new kind of game-mode, that is actually a different game. The game is a memory game. The user sees an animation formed by different colored shapes that quickly appear and then disappear and he has to remember what happened and then, after the animation is over, say what he saw. In this game, also, I would add different difficulty levels. Is it okay if I do that instead of a login option?

**Comment by Alex-Cosma** [comment]
Sure

**Comment by vatavului** [comment]
Here is a close to final version of The Anoying Game. I added my other game, the one I mentioned earlier, to the main project. I still need to re-read the code and everything, and to correct some little bugs maybe. I also tried to make it look nicer:)) Can you see the images, by the way? I'm not sure if I did that right.

**Comment by Alex-Cosma** [comment]
- your code is not formatted!
- `BigController` - terribly bad class name 
- 
```
		private GameController theGame = new GameController();
		private ShapeController theGame2 = new ShapeController();
```
Terrible naming as well
- The `ShapeController` class is almost 100% the same as `GameController` class. Parametrise them and simply make 1 class out of it and maybe name it `DifficultyChooserController`.
- Generally the architecture is really fine, with the controllers and stuff, easy to read, but yes, the code seems a bit messy, please clean it up!

**Comment by vatavului** [comment]
Okay! I'm doing that. It's because I worked on the second game separately and I just glued them together a little too mocănește. I'll clean it up! Thank you!

**Comment by vatavului** [comment]
Hi, Alex. Happy new year!
I did the long-awaited code-clean-up and I hope I have less shitty names and other mistakes. I have only one main Controller class right now. I took your advice and I merged the old GameController and ShapeController classes into DifficultyChooser. You were right, they were almost the same, they were just calling to different Menus - which made me realize that the old menu classes were actually very similar too, so I just went with a new Menu class and got rid of ShapeMenu. I also checked the other classes too and corrected some stuff.

**Comment by Alex-Cosma** [comment]
```
		private DifficultyChooser colorGame = new DifficultyChooser();
		private DifficultyChooser memoryGame = new DifficultyChooser();
```
I don't think yuo need two different variables here, one will suffice, don't you think?

**Comment by Alex-Cosma** [comment]
```
			colorGameButton = chooser.getButton1();
			memoryGameButton = chooser.getButton2();
			colorGameButton.addActionListener(new ChoiceListener());
			memoryGameButton.addActionListener(new ChoiceListener());

```

Same here. Why not just have 1 button, the functionality is exactly the same

**Comment by vatavului** [comment]
Hm, that's right! I only needed one DifficultyChooser variable.
What I do not quite understand is why I don't need two different buttons. The ChoiceListener says that if the button is the one referring to the color game, it opens up the color game, and if it's the other one, it opens the memory game. 

( Or maybe it would have been more recommended to create a different ActionListener for the second button and have two listeners, instead of only one that verifies the button and does the right thing? )

**Comment by Alex-Cosma** [comment]
Oh no, you're right on the buttons, nevermind.

**Comment by vatavului** [comment]
Okay! 
Now I fixed the very, very, important problem of spelling 'annoying' wrong for such a long time. Well, I did not rename the project because that seems too have too many consequences but I took the time to redo all the pictures in Photoshop and add the extra 'n'. I know, irrelevant but I could not help it. Sorry.

**Comment by Alex-Cosma** [comment]
:+1:

**Comment by vatavului** [comment]
Is it all-right now?

**Comment by Alex-Cosma** [comment]
Dada

**Comment by vatavului** [comment]
Gracias.

**Pull request merged**
