### PR TITLE
Battelship

### PR DESCRIPTION
**Pull request by todericidan**
I will finish Ai hitting system tomorrow and i'll get rid of the commented code that apparently I forgot to delete.Sorry

### CODE REVIEW

**Comment by todericidan** [comment]
I finished the Ai hitting system. Would you mind checking it and tell me if there are things to be changed?

**Comment by Alex-Cosma** [comment]
Nope, there's nothing I want to add here. Patch it together with a good UI! 
Good luck

**Comment by todericidan** [comment]
hope you like the UI

**Comment by Alex-Cosma** [comment]
Looks really great! but:
- please centre all the frames on the screen (`frame.setLocationRelativeTo(null);`)
- I couldn't place my own ships! they just didn't appear on the board so I used random which worked. Is that also a bug or did I miss anything?

**Comment by todericidan** [comment]
when you place you ships you have to click on a boat type then on the orientation and on the board for the location and then click done

**Comment by Alex-Cosma** [comment]
Ah, oh..
How about throwing some cool shadow on the buttons while hovering over them with the mouse when placing ships? :grin: 
Use [this](http://stackoverflow.com/questions/22638926/how-to-put-hover-effect-on-jbutton)

**Comment by todericidan** [comment]
https://www.google.ro/search?q=how+about+no+meme&espv=2&biw=1920&bih=1067&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjQ99fzrYTKAhUBFw8KHXvfALoQ_AUIBigB#imgrc=mDKpCc_1na5iYM%3A

**Comment by todericidan** [comment]
just joking, I'll try it after new year's eve

**Comment by Alex-Cosma** [comment]
:disappointed: fine..

**Comment by todericidan** [comment]
and about the shadow, should it be for example for the placement board and the hunting board to show exactly which button can be pressed?

**Comment by Alex-Cosma** [comment]
just the placement board. when you select a ship and a direction and hover the mouse over a square, the squares which are to be filled if you click on that specific square should be highlighted

**Comment by todericidan** [comment]
that will be challenging,hope I will succeed in doing it.

**Comment by Alex-Cosma** [comment]
If programming was

**Comment by todericidan** [comment]
Calin had some troubles with uploading his project and I have uploaded for him

**Comment by todericidan** [comment]
Thank you for your help and time and also Happy New Year's eve! May the force be with you,always!

**Comment by Alex-Cosma** [comment]
What troubles..? where did you put it? it should be in his folder :\

**Comment by Alex-Cosma** [comment]
Nevertheless, happy new year!

**Comment by todericidan** [comment]
it's in the same pull request, in project java sub-folder, which is in the folder with my name

**Pull request merged**
