### PR TITLE
othello game project

### PR DESCRIPTION
**Pull request by dianagabrielapopescu**
it is not yet done. i have to review some methods that are not working properly...

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
So the architecture of the code is good, really well done on that part.
There are however some things which might be improved.

**Comment by Alex-Cosma** [comment]
What if you'd create a class which will take care of all these `thereExistsAtLeastOnePossibleMoveForThisColorAndThisPosition` things?
I feel like that method can be broken into more smaller methods and it can certainly be written more efficiently.

**Comment by Alex-Cosma** [comment]
PS: I think it would be very nice to be able to change the board size and have the game work just as well - I tried setting `ROWS = 18;` and `COLS = 18;` but it stopped working once I made any move.

**Comment by Alex-Cosma** [comment]
Overall, nice and clean code!

**Comment by Alex-Cosma** [comment]
Yes but I don't think it makes sense to have the `Controller` extend `ThereExists`. Why not simply create an instance of it in the `Controller` class? (use composition, not abstraction in this case)

**Comment by Alex-Cosma** [comment]
Everything else does look slightly cleaner :smile:

**Comment by dianagabrielapopescu** [comment]
i tried to apply all your suggestions. the game now actually works for variable sizes of the board :)

**Pull request merged**
