### PR TITLE
My first attempt

### PR DESCRIPTION
**Pull request by bogdanstupariu**
Here is the first version of my project. 
I hope the next one will be the last one. 
I had a lot of problems with both the functionality and graphics. I tried to use as much as i could what we've learned at the courses, but from a point, it was impossible. 
There are parts of code taken from other sources (such as the running engine - i can't understand it but i tried for 2 days to create smth like it and it was a mess).
I also tried to make the game realistic (from the functionality point of view - the ball direction perfect, etc.). After i studied all the mathematics on the internet, i realized it is toooo complicated (for me, at least :)) ).

Tomorrow i'll try to create a menu with two options: 1. 1vs1 (implemented now) 2. vs Computer (implemented hopefully tomorrow).

As soon as the feedback(and i know there will be a lot) came, i'll try to change the code before going to party for the new year's eve.

Have a great Holiday!!!!!

### CODE REVIEW

**Comment by bogdanstupariu** [comment]
I updated the code. Succeeded to add a menu, some sound effects, resolved some (many) bugs, and most important, make the code look nice.

**Comment by Alex-Cosma** [comment]
First off, thank you! I hope you are having a great holiday yourself.

**Comment by Alex-Cosma** [comment]
You have some libraries which are referenced in your project - that is just fine, however I don't have them locally so I cannot run your program. Please put the libraries inside your project folder and reference them from there and then commit the changes and push them to git so the libraries will pop there as well

**Comment by Alex-Cosma** [comment]
Without running the project, here are a few thoughts:

- having a `Player` and a `Player2` class is by definition wrong. You should simply instantiate 2 instances of the `Player` class and not have them separated like this. What is the purpose of the second `Player2` class? The code is basically the same, only some colour and positions are changes - these can be passed as constructor parameters!
- Then you have the `GameObjects` class which, well, extends a JFrame. Why does it extend `JFrame`? I don't see it use any `JFrame` methods or attributes there. The question to ask is: `is every GameObject a JFrame?` if not, then surely this hierarchy is not good.
- The `GameObjects` class models one single object, not more, so it should be named `GameObject` even though it will be extended by more than 1 subclass.
- `Ball extends GameObjects` --> `Ball extends JFrame`. Are you sure that the `ball` is a `frame`? :thought_balloon: 
- You might also consider breaking the classes into more than 1 package

You have still some work to do on your class design but I'm confident you'll manage it just fine :+1:

**Comment by bogdanstupariu** [comment]
Here is the new version.
1. Libraries in same folder and referenced - checked so now it should work. 
IMPORTANT. TO TEST THE GAME, SELECT THE MULTIPLAYER OPTION FROM MENU BECAUSE THE vs John CPU is based on the AI I have not implemented yet. So, Player2 in that case is not moving at all.
2. GameObjects extends JFrame eliminated - checked - Firstly i tried another implementation and i forgot to delete "extends JFrame". It makes a lot of sense not to have that code part.
3. Renaming GameObjects - i forgot to do that. 
4. Broke classes into packages. I'm not sure if my logic is good in this case. I'm waiting for feedback.
5. Player and Player2 because i have no idea how to implement different Keyboard controls for them if not and have no idea how to implement the AI for Player2.

**Comment by Alex-Cosma** [comment]
Uh, are you sure you've committed those libraries? I only have a folder called `lwjgl` in the Libs folder and that does not contain any libraries...

**Comment by Alex-Cosma** [comment]
Much better package placement, still. I do not understand the problem of not having a `Player2` class.

**Comment by bogdanstupariu** [comment]
From some reason i can't upload/sync the folder containing the missing libraries on github. Also can't send them with yahoo or gmail (the attachment is blocked - from some reason again). 
I send the libraries with wetransfer

**Comment by Alex-Cosma** [comment]
Just put the libraries (as `.jar`) in the root folder of the project, commit + push

**Comment by bogdanstupariu** [comment]
I made all the sound codding as comments until i find a way to make the sounds work without .jar files, in order for you to be able to play the game. Hope that now it is working.

Have a great end of the year!

**Comment by Alex-Cosma** [comment]
Great! It looks very cute, good work, but again, please take note of all the comments I wrote above.

**Comment by bogdanstupariu** [comment]
Updated the code with
1. Game Object instead of Game Objects
2. Player2 class deleted - Player class used only

**Pull request merged**
