### PR TITLE
This is the first version of my Puzzle project.

### PR DESCRIPTION
**Pull request by nagyhanna**

### CODE REVIEW

**Comment by nagyhanna** [comment]
And by the way, I wish you a happy-merry Christmas :)

**Comment by Alex-Cosma** [comment]
Aw, thank you, Hanna! A very merry Christmas to you as well.

Ps: I think you forgot to commit the `Image.png`!

**Comment by nagyhanna** [comment]
it should be in \PuzzleProject\bin\model

**Comment by nagyhanna** [comment]
I verified, all images are there :)

**Comment by Alex-Cosma** [comment]
Ok, but the bin folder is ignored by git. Don't put them there. That folder only contains the compiled `.class` files. Put them in a folder in the root directory of the project called `resources` or `res`

**Comment by nagyhanna** [comment]
I hope now everything is in its right place :-s  ^_^

**Pull request merged**
