### PR TITLE
Java Project - Redstone Simulator

### PR DESCRIPTION
**Pull request by alexh95**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
A short documentation - great start

**Comment by alexh95** [comment]
I've edited the md in git before pushing my local data and everything was broken, this is just to resync. I had begun adding a create view to Zoosome but I'll continue that once I finish the project.

**Comment by Alex-Cosma** [comment]
Good, carry on

**Comment by alexh95** [comment]
Here it is. I know there are inconsistencies that I haven't ironed out yet, but can I modify the code after the deadline if it consists of things that don't change the logic of the game (accelerator for the menu and hotkeys; which will probably mean splitting some methods)

The biggest problem is the performance. It wouldn't be minecraft otherwise :laughing:
If I had more time I would compose the top level image on multiple threads (i.e. for every block) and make the filters static, or make individual textures for every state. Is that a great idea? In what way could I improve the performance (very visible performance drop while panning)

**Pull request merged**
