### PR TITLE
Chess help

### PR DESCRIPTION
**Pull request by vblana**
The eternal null pointer exception at Main.UserInterface.paintComponent(UserInterface.java:43)

### CODE REVIEW

**Comment by vblana** [comment]
Most of the methods and attributes are static because they have to be that way in order to be accessed from MouseReleased.
Anyway, i can't figure out why there is a null pointer exception.
In main, you can see that chessBoard[0][0] is a Rook ,but in paintComponent it throws an exception:/

**Comment by Alex-Cosma** [comment]
It does not throw the exception at [0][0]. It throws it at [2][0]. Use the debugger.

**Comment by Alex-Cosma** [comment]
_Most of the methods and attributes are static because they have to be that way in order to be accessed from MouseReleased._
- that is NOT a good reason for them being static!

**Comment by vblana** [comment]
But why would i want to instantiate MainClass when i'm only using one board anyway?

**Comment by Alex-Cosma** [comment]
You don't have to instantiate the main class, but every variable there is static. 
Also, you have a `Board` object and then a `chessBoard` matrix. Why isn't the `chessBoard` only in the `Board` object?

**Comment by Alex-Cosma** [comment]
The getter from the `Board` class is useless as the `chessBoard` is public and static anyways.
```
	public static Piece[][] getBoard() {
		return chessBoard;
	}

```

**Comment by Alex-Cosma** [comment]
You should have only one reference to the chess board in one place in the application and that should be in the `Board` class. No where else should you have a matrix for your chess board. Single responsibility, remember?

**Pull request closed without merging**
