### PR TITLE
Project pong

### PR DESCRIPTION
**Pull request by negreavlad95**
I think my project is done. Is there anything else that should be implemented?

### CODE REVIEW

**Comment by negreavlad95** [comment]
Those files:  pong_2141....txt etc. were created by an eclipse extension and you should ignore it.

**Comment by Alex-Cosma** [comment]
So cool! Hah, very nice, but here are a few improvements which you should work on.

**Comment by Alex-Cosma** [comment]
Great work for now! The game is really cute

**Comment by Alex-Cosma** [comment]
https://www.youtube.com/watch?v=1wD2CdFlDaE
+
https://github.com/Jaryt23/PongTutorial/tree/master/pong

Unfortunately your code is almost 100% copied from here so I will invalidate your project.

**Pull request merged**
