### PR TITLE
Gin-Rummy - first version

### PR DESCRIPTION
**Pull request by CorinaAlb**
Hi, this is my project. Can you give me some advice on how to organize the code better ? It works best on Samsung Galaxy Core 2 (emulator) and is locked in landscape view. Also, I have a problem with the random numbers generator - I tried to avoid duplicates, but my method doesn't work.

### CODE REVIEW

**Comment by CorinaAlb** [comment]
never-mind the first version, it crashes :D. the last one works

**Comment by Alex-Cosma** [comment]
I've merged this by accident - simply create a new pull request :relaxed:

**Comment by CorinaAlb** [comment]
ok, also, I have a question, when and where should I present my project?

**Comment by Alex-Cosma** [comment]
Some time in the first 2 days of the extra-exam session. When I'll know more details, I'll be sure to let you know!

**Pull request merged**
