### PR TITLE
My project - Backgammon

### PR DESCRIPTION
**Pull request by JucanDiana**
Hello! This is my game, but I have a problem and I don't know how to fix it!
When a player roll the dice, the dice appear and it is possible to make a lot of moves corresponding to dice. I tried some things, but it didn't worked.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
So, first off, I don't think you've committed the resource files (images). If you placed them in the `bin` folder, careful! That folder is completely ignored by GIT as it should always contain only compiler generated code and nothing else.
Please create a folder called `res` in the root folder of the project and place every resource (image/sound) there.

**Comment by Alex-Cosma** [comment]
Your code does look pretty nice and clean from what I see, but keep in mind. I will not be able to help you bugfix your code... If I'd had to do this for everyone it would take ages and unfortunately, I cannot spare ages. I will of course look over the code thoroughly and tell you at a more higher level what I think you can improve.

**Comment by JucanDiana** [comment]
I  created a folder res. I hope it's ok now! And I solved my problem. :)

**Comment by Alex-Cosma** [comment]
I do see that you created that folder, but did you also locally remove them from the `bin` folder and test to see if the images get loaded from the `res` folder?
I get a `null pointer exception` when running your game here:

```
		this.imgBackground = new ImageIcon(urlBackgroundImg).getImage();
```
(at gui.BackgammonGui.<init>(BackgammonGui.java:51))
which basically means that it couldn't load the image

**Comment by JucanDiana** [comment]
I know that error. It is because the images should be in the same place with the classes where the images get loaded ( those with .class). I have 6 images with the dice(face1,..face6), that should be in bin folder, than in logic folder, and 3 other  images named gameboard, redPiece and whitePiece that should be in bin folder, than in gui folder.
If you download my project and then it will be imported in eclipse, please move the images from res to the corresponidn location.. It should work! If not, tell me and I will change the code, even if I tried and I got error , but I will try again

**Comment by Alex-Cosma** [comment]
The images should not have to be in the `bin` folder! Make it such that they are loaded only from the `res` folder

**Comment by JucanDiana** [comment]
I tried to change the code so that the images are loaded from the res folder , but it didn't worked. Always the same error, null pointer exception

**Comment by Alex-Cosma** [comment]
Uite, încearcă [asta](http://stackoverflow.com/questions/6845231/how-to-correctly-get-image-from-resources-folder-in-netbeans) sau [asta](http://stackoverflow.com/questions/1978445/get-image-from-relative-path) sau ai putea chiar să întrebi un coleg care a mai făcut asta. No shortcuts :relaxed:

**Comment by Alex-Cosma** [comment]
A very difficult game to implement but you did a good job - everything works now.
Nu știu exact cum merge chestia cu scosul, nu îmi dau seama dacă ar trebui să apară undeva piesa scoasă sau nu, nevertheless, îmi arăți tu la prezentare.

**Comment by Alex-Cosma** [comment]
There's not much I can add here. It's a complicated game (logic-wise) so of course, the code will be rather complicated as well.

Do the UML diagram and you'll be done!

**Comment by JucanDiana** [comment]
Trebuie sa pun diagrama UML pe git sau e suficient sa o am la prezentare?

**Comment by Alex-Cosma** [comment]
Cum vrei. Dacă o aduci doar la prezentare, dau `merge` acum la pull request și e ok. Dacă vrei să o pui aici, dau merge după ce o pui.

**Comment by JucanDiana** [comment]
O aduc la prezentare ca nu e facuta.

**Comment by Alex-Cosma** [comment]
No problemo. Până una alta, la mulți ani și un an nou fericit!

**Comment by JucanDiana** [comment]
Multumes la fel! An nou cu bine! :)

**Pull request merged**
