### PR TITLE
Breakout

### PR DESCRIPTION
**Pull request by iacobvlad**
The project is in the commit that says " This is the actual project" .The previous 2 contain some irrelevant .txt files.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Hahaa it's so cute with the sounds and all that :relaxed: Lovely work.

There are only 2 things I have to add here:
- You will have to replace this
`NewGameButton.setIcon(new ImageIcon("E:\\UTCN\\JAVA\\workspace\\TestDemo3\\play.png"));`
with a relative-to-project path. Simply create a folder `res` or `resources` in which you can put all your images and sounds and place it in the root folder of the project. Thing is, you can imagine, I tried playing your game locally but because I obviously do not have this absolute path on my machine, the image did not get loaded.

- don't forget to remove any unused variables throughout your code - surely, Eclipse tells you which ones they are.

**Comment by Alex-Cosma** [comment]
Great job overall with this. Don't forget about the UML diagram and you'll be done

**Comment by iacobvlad** [comment]
Thank you so much Alex! I ll commit the UML diagram surely,but I'm afraid I can't do that sooner than 1/2Jan for I'm leaving the town these days.It's ok?

Vlad Iacob 
30422,CTI
Cluj-Napoca,Romania

**Comment by Alex-Cosma** [comment]
No rush. You can even bring it at the lab next week

**Pull request merged**
