### PR TITLE
Added project

### PR DESCRIPTION
**Pull request by bbeniamin**
Hello. 
I've done some work on the project and things went pretty on until now, but I just encountered a problem that I couldn't find a solution to. I started working on the logic of the project, namely the GameEngine class. I know it probably shouldn't be static but I have just begun working on it and it's a bit easier to test it like this. So the problem

### CODE REVIEW

**Comment by bbeniamin** [comment]
Note to self: pressing enter creates the pull request, not a new line. The problem is this: while trying to place a settlement, for example, I want to listen for mouse clicks on the nodes and send the first node clicked after the user presses the "place settlement" button as a parameter to the placeSettlement method. But I did not really know how to do that, so the solution I came up with is sort of ghetto but was supposed to work: I have listeners on all the nodes and every time the user clicks one it changes a variable. I then have a getNodeClicked that is supposed to "detect" when the last clicked node has changed and then return the clicked node. But instead it freezes my program. I tried to find something on google but it didn't really help. So I guess either my logic is bad, and this isn't supposed to work like this at all, or I don't know how to google stuff. Could I get a bit of help?

**Comment by Alex-Cosma** [comment]
So first off, the game looks great!! The menus are simple and clean and the board looks crispy clean.
Now I can't really get into bugfixing your code. I can (and will) of course give you some tips on how to improve your code.

**Comment by Alex-Cosma** [comment]
I am honestly impressed by the amount of code you pulled and by the fact that it's actually pretty clean. Kudos, young padawan. Yea, sure, you have those static methods there but they aren't anything to worry about, they can easily be made non-static.

I do hope you get it working properly by next week, but nevertheless, wonderful job!

**Comment by Alex-Cosma** [comment]
ps:
The `Pics` folder usually stays out of the `src` package and is placed in the root folder of the project, but again, no biggie here.

**Comment by bbeniamin** [comment]
Just noticed that the saved games do not load. They did an hour ago, I will try to look into it until wednesday.

**Pull request merged**
