### PR TITLE
Fluffy the Cat with GUI

### PR DESCRIPTION
**Pull request by kovacsgellert**
Every function present in the console version is also implemented in the GUI version but the code may not be the most beautiful.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Good work!

**Comment by Alex-Cosma** [comment]
What a great job you've done with the Snake! One of the best cleanups I had :smile:

**Comment by kovacsgellert** [comment]
Thank you. :smile: If only I could apply the same talent when writing code from scratch. Seemingly it's easier for me to clean others' code up.

**Comment by Alex-Cosma** [comment]
What makes you say that? 
Trust me when I tell you that given enough time and practice, you will get as far as you want to. Remember, you've just only started with OOP! Even if the concepts are simple to grasp they are very difficult to master and juggle with.

**Pull request merged**
