### PR TITLE
This is my game.

### PR DESCRIPTION
**Pull request by HFiras**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Very cute! It works great as well, good work. :relaxed:

**Comment by Alex-Cosma** [comment]
Here are a few remarks:
- first off, you should think about breaking the classes into more than one package
- These three:
```
	public static Player player;
	public static Level level;
	public static SpriteSheet spritesheet;
```
should not be static. 

I know, it's easier, yes, but remember - this is not _procedural_ programming, we are dealing with objects here! Every `Game` should have a `player`, a `level` and a `spritesheet`. Not all instances of `Game` should have the same `player`, `level` and `spritesheet`. You should couple the classes in such a way that you do not need those static variables.
Remember, static gives a different conceptual meaning to things! The same applies for `STATE`.


I think you can concentrate on these two things for now and later, we'll see what more (if anything) can be improved.

**Comment by HFiras** [comment]
Scuze, nu te uita inca la el ca am o eroare

**Comment by HFiras** [comment]
I took care of those static objects, but I had to deal with the null error when I was breaking the classes into 2 packages and I can't solve it. I know is because of the image that needs to be imported, but I can't figure it out.

**Pull request merged**
