### PR TITLE
ProjectFirstVersion

### PR DESCRIPTION
**Pull request by andreeaonaciu**
Hi ! :)
   This is what I did so far... I want to ask you if the design of the classes is ok ? ( maybe there is too much going on in the PlayActivity ).  I will also try to keep the score,to have a button to reset the game and to exit. I will also improve the design of the game, there are two buttons with no sense, but (because of the relative layout) if I erase them, the others change their positions.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Good work so far. I don't think the `PlayActivity` has too many things going on, but they could be slightly better written. For example:

```
        if (whosNext)
                                    message.setText("Player 2, put bean on the board !");
                                else
                                    message.setText("Player 1, put bean on the board !");
```

You have constructs like this in a lot of the places. Maybe you can find a way to write this a bit more elegant? Maybe create a `Player` class and have two instances of it, have a `currentPlayer` local variable and then well, you can use your imagination :smile:

**Comment by Alex-Cosma** [comment]
Even in the `Game` class, you have stuff like:

```
    private int nrOfBeansLeftPlayer1;
    private int nrOfBeansLeftPlayer2;
    private int nrOfBeansInGamePlayer1;
    private int nrOfBeansInGamePlayer2;
```

Which might actually be part of a `Player` class, right?

```
public class Player {
    private int nrOfBeans;
    private int nrOfBeansInGame;
    + any other attributes
    // getters and setters ... 
}
```

**Comment by andreeaonaciu** [comment]
Thank you for your advice ! I did some changes now, hope it looks better :)

**Comment by Alex-Cosma** [comment]
Ok, great. I like it. Make sure you'll have a 'menu' with the 'New Game' option.
Now moving a bit forward:
- try out your game on different screen resolutions (even tablets). Does it scale nicely? If not, do you think you can work on that?

**Comment by andreeaonaciu** [comment]
Happy new year !!! :) I did a menu, but I still do not know how to make the app appear nicely on different screen resolution, I read that maybe I have to do different layouts, for different sizes of devices, somewhere else it says :" In most cases, you can ensure density independence in your application simply by specifying all layout dimension values in density-independent pixels (dp units) or with "wrap_content", as appropriate. The system then scales bitmap drawables as appropriate in order to display at the appropriate size, based on the appropriate scaling factor for the current screen's density." ...I will still try to work on this, if I have enough time left. Please, tell me, if there are other things I need to improve.... and thank you for all!!!

**Comment by andreeaonaciu** [comment]
PS: I tried the app on a tablet, and yes, it looks horrible...

**Comment by Alex-Cosma** [comment]
Don't worry about it. You're done here, happy new year to you as well.

**Comment by andreeaonaciu** [comment]
I heard from Roxana, that we have to do the UML diagram in some program, is that correct ?

**Comment by Alex-Cosma** [comment]
Uh, not really, no? you can do it in whatever program you want or by hand.. your choice.

**Comment by andreeaonaciu** [comment]
Ok then, and If I make it by hand, I have to take it a photo, and put it here ?

**Comment by Alex-Cosma** [comment]
Nope, bringing it will suffice.

**Comment by andreeaonaciu** [comment]
Ok, thank you very much !!! :)

**Pull request merged**
