### PR TITLE
The problem

### PR DESCRIPTION
**Pull request by andinicolescu**
Here's the code! Thank you!

### CODE REVIEW

**Comment by andinicolescu** [comment]
How do i add only one commit??

**Comment by Alex-Cosma** [comment]
Commit your changes and then push them. They will automatically appear on this pull request. You don't have to close it.

**Comment by andinicolescu** [comment]
Solved the problem yesterday but forgot to upload the new project. Singleton did a really nice job! thanks! Now only the interface of the difficulties left. I'll be back with updates

**Comment by andinicolescu** [comment]
Question: This is the structure of the accounts.txt file:
Andi //account
12934021301 //hashcode of the password
301 //the score

This is the thing: when your score is updated the method looks for the past score "301" and replaces it with the new score (let's say you won so you have +20) "321", but he also modifies the hashcode and distroys my password. What to do? Give up on hashcode? Make a file only with scores? if 2 players have the same score it will modify both their scores. Thanks!

**Comment by Alex-Cosma** [comment]
I think you should consider not having a text file at all, but rather, saving and loading a serialized `ArrayList` of `Accounts`. I think you'll find it a lot more elegant this way -> no more string parsing and so on.
Check out [this link](http://avajava.com/tutorials/lessons/how-do-i-write-an-object-to-a-file-and-read-it-back.html)

**Comment by andinicolescu** [comment]
Saving an object. Nice. I'll think about it. Then I'll change the score using just setScore method of Player class. Thanks!

**Comment by Alex-Cosma** [comment]
Yes, that would be the general idea, and then, at the end of each game you can save and thus overwrite the object.

Upload the code so I can see what you've done so far!

**Comment by andinicolescu** [comment]
I have redesigned the whole project, renamed methods and variables.
There is an interface that is implemented by all the difficulties and the Easy and Normal classes also extends an abstract class with the methods needed in order to execute a move.
I think I covered everything you said. Waiting for your opinion!

**Comment by Alex-Cosma** [comment]
In your last commit, you actually deleted all the source (`.java`) files! :laughing:

**Comment by andinicolescu** [comment]
Just checking to see if you're really looking over the project :))

**Comment by Alex-Cosma** [comment]
General stuff:
- all methods should start with a lower case character
- there are still quite a few variables with really bad names (`a`, `b`, `c` ... )

**Comment by andinicolescu** [comment]
Just a little problem when saving the new score in accounts.ser after I won (when someone wins their score is updated +20. I solved the other problems.

**Comment by andinicolescu** [comment]
Solved it. I'll upload soon the new project

**Comment by Alex-Cosma** [comment]
One more thing which I forgot to tell you about.
The audio/visual assets should never be placed in `source` packages. Rather, you can place them in folders outside your source packages. In the source packages you should only have source files.

**Comment by Alex-Cosma** [comment]
I merged this for now.

**Pull request merged**
