### PR TITLE
Tetris

### PR DESCRIPTION
**Pull request by Popdanvlad**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Arată chiar drăguț, dar uite totuși niște chestii care ar merita schimbate: (voi scrie în engleză să nu tot îmi trec tastatura din engleză în română pentru diacritice)

- format your code!!! all of it! `Ctrl + Shift + F`
- The `gameOver` class should maybe be given a better name like `GameOverFrame`
- The attributes in the `gameOver` class can all be `private` and `non-static`!
- The `readFile` class should get a better name as well, like `ScoreFileReader` or something
- line 64 @ Main class
```
    if (gameOver == false) {
```
is redundant because you already have that check at line 55. 
The whole logic behind this class is really messed up. Way too many static variables!

- In the `TetrisController` class you have
``` 
		game.Game.addKeyListener(this);
```
Why not simply make the `Game` class extend `JPanel` and then you could have simply written `game.addKeyListener(this);`
- Remember the naming conventions for variables. They should start with lower case letters and use camel casing.
- Why does your `Move` class extend `Main`? How is a `Move` actually a.. `Main`, conceptually speaking. I think this whole part of the application is really badly written. 
- There are a lot of *magic numbers* in the `Move` class, for example, here:
```
	public static void adjust() {  //REWORKED
		for (int i = 0; i < 10; i++) {
			matrice[i][2] = 200;
			matrice[i][12] = 200;
		}
	}
```
Why 200? And why 2, and 12? What are those?
- I think the logic in the `Move` class is very sophisticated (in a bad way)

I think it's good that you tried to use an MVC (model-view-controller) type of architecture however please keep in mind, you are coding in the object oriented paradigm, not procedurally. You should have absolutely no static variables unless they conceptually should be static!

ps: nu **fii** foarte dur :grin:

**Comment by Popdanvlad** [comment]
I've solved most of the issues. I understand that I could get rid of the static methods by creating new objects, but I think that requiers a lot of work to do, and now there's not enough time left I'm afraid.
 I'm aware that I did not get the MVC design concept properly, but since I'm not that advanced in this area this is just an early attempt. 
Thank you for your understanding!

**Comment by Alex-Cosma** [comment]
That does require some work to be done, yes, but it is essential to OOP. You've more or less basically have just written a procedural program :worried:

**Comment by Popdanvlad** [comment]
I'll try to work on it as soon as I get to Cluj today. If I manage to get it working today I'll be uploading it this evening. 
What happens if I will not be able to finish it today, will my mark go down a little bit or I will not get a passing mark for the project?

**Comment by Alex-Cosma** [comment]
I'm not sure if you'll get a passing mark with this code to be honest, maybe!

**Comment by Popdanvlad** [comment]
I'll try to make some changes to it this afternoon.
I know it's not very OOP style, but at least it is entirely my code, I've managed to handle all the working tasks and I think it's worth at least a 5 or 6 taking into account that this is my first semester of oop. I was very entangled with the structural style of coding.

**Comment by Popdanvlad** [comment]
I've made a few changes in the project trying to make it more OO. I've drawn the UML too for the project. I couldn't remove some of the static variables because when I first started this project I haven't got a true understanting of the Object Oriented Programming. I've tried these days rethinking it but the structrural programming style is too strong with this one. I hope though you will appreciate my true efforts in developing this project, and that I manage to get everything working, not in the best way, that's true, but there was a lot of hard work in doing this, and I've learned a lot during the developing.
Best wishes, Dan Pop

**Pull request merged**
