### PR TITLE
Java Project

### PR DESCRIPTION
**Pull request by botapaul**
Te rog sa imi verifici proiectul si sa-mi spui daca mai trebuie sa fac ceva la el. Multumesc!

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Holy Molly, please format your code!

**Comment by Alex-Cosma** [comment]
```
	private String path="D:\\eclipse\\BlackJack\\src\\";
```

Loading images like this won't do. I cannot play it locally because, of course, I do not have this absolute path.
You will have to put all your images in a `res` or `resources` folder which should reside in the root folder of your project. Then, you can simply use a relative path to load the images

**Comment by Alex-Cosma** [comment]
Do these changes and I'll look at your project afterwards.

**Comment by botapaul** [comment]
I arranged my code and changed the images location.

**Comment by Alex-Cosma** [comment]
Great! The game works fine now. Again, please put all your images in a `res` or `resources` folder which should reside in the root folder of your project. Right now, when I open your project in Eclipse, I have to scroll down a lot in order to not have only cards on my left project explorer tab.

Code wise, I think your `Interface` class knows too much and handles too many things. Do you think you can break it in more than one class? Maybe use the controller pattern here?

**Comment by botapaul** [comment]
I've tried to split Interface class, but it didn't  worked well. I had some errors.

**Pull request merged**
