### PR TITLE
This is what I have done so far! Hope it is ok

### PR DESCRIPTION
**Pull request by tufisii2006**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
First off, the icons should be placed outside the `source` package. Create a `res` or `resources` folder in the root folder of your project and place them all there. Make sure that things still work after you move them there.

**Comment by Alex-Cosma** [comment]
I am very curious why you chose to implement the board with `graphics` and drawing stuff and not with a simple matrix of `JButtons`, using swing. Care to explain?

**Comment by Alex-Cosma** [comment]
Whilst playing the game, I encountered a few problems:
- the click is not accurate. When I click on a button, the one bellow it gets toggled
- when I click on a mine, I get no message that the game is over
- I have no way of telling how many `flags` I have left. 

You can safely copy the design of the original minesweeper. I think it contains all the elements it needs and you won't have any copyright problems :smile:

**Comment by Alex-Cosma** [comment]
Your `GameTiles` class actually mdels a single `GameTile`, not more

**Comment by Alex-Cosma** [comment]
You might also want to break your code into more than 1 package.

**Comment by Alex-Cosma** [comment]
You still have some work to do, but I'm confident you'll be able to finish it in time

**Comment by tufisii2006** [comment]
Update: I manage to do the first "quest".I changed the gifs from a package to a SourceFolder.Tricky but not imposible.I also changed the name of GameTiles.
I knew I had some bugs and errors.The problems with the "clicks" is that it works on coordonates,and those are not eficient(yet).For now,top left coordonates are not (0,0) as it should be.
About making more packages,I will try but not promise :D !
Thanks for looking on my code ^^

**Pull request merged**
