### PR TITLE
My Dodger Java project

### PR DESCRIPTION
**Pull request by GiurgiumanAndrei**
Hello,can you please check my project and tell me if there is anything  i can correct?

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
What a great job you did! Very nice and very clean code. There are a few remarks which I would briefly want to add:

- You have used the `Commons` interface as a place to keep 3 constants. Now this is not very conceptually correct because that interface has no meaning, it's just a .. container. What I would suggest you do is transform that into a class, and instead of using `... implements Commons` you will delete this and statically import the constants wherever you need them, like this:
```
    import static graphicalUserInterface.Commons.BOARD_HEIGHT;
    import static graphicalUserInterface.Commons.BOARD_WIDTH;
    import static graphicalUserInterface.Commons.DELAY;
```

- You've chosen to set the little monsters invisible and thus not paint them on the screen by checking:
```
			if (baddies.get(i).isVisible()) {
...
			}
```

This way however, they remain in the array list and that clogs memory - A LOT, keeping in mind that the game might run for ages (theoretically). If you are to go through an array list which contains 1 million entries each 0.5 seconds for example, I assure you, even if all you do is a simple if statement, that will take a lot of time, and in your case, useless time!
I would suggest removing the baddies from the array list after they become 'invisible' to the player.


That would be all from me, again, very well done.

**Comment by GiurgiumanAndrei** [comment]
Would this be the correct approach to remove the monsters from the array list? I've made the change regarding the  Commons interface aswell.

**Comment by Alex-Cosma** [comment]
Yep! good work

**Comment by GiurgiumanAndrei** [comment]
Thank you!

**Pull request merged**
