### PR TITLE
Assignment 2.2 - Zoowsome 1

### PR DESCRIPTION
**Pull request by mariahada**
A *bit* late, but here it is.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Lovely work otherwise. Glad to have you 'back'

**Comment by Alex-Cosma** [comment]
Yey! Good work!
And congrats for yesterday. You guys did a great job. Keep it up!

**Comment by mariahada** [comment]
Thanks and thanks! We did our best. I hope you enjoyed the competition.

**Comment by Alex-Cosma** [comment]
It was quite fun

**Comment by mariahada** [comment]
I'm glad to hear that

**Pull request merged**
