### PR TITLE
SudokuGame

### PR DESCRIPTION
**Pull request by DariLupea**
This is what I have done until now. I thought that it should be better to firstly create a solution for the game and then start to implement the interface.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
You've uploaded only 1 file

**Comment by DariLupea** [comment]
yes, this is what I have till now

**Comment by Alex-Cosma** [comment]
Wow, you have 4 classes in this hierarchy:

```
     UserGame  
               |
           CheckSolution
                    |
               GenerateSolution
                         |
                    GameGenerator
```

And well, my question is... why?

If inside a `CheckSolution` object you need a `UserGame` object, then you can pass a reference as parameter to the constructor of `CheckSolution` but I honestly don't see why `CheckSolution` is a type of `UserGame` and furthermore, why that hierarchy holds. Conceptually, does it make sense to have them as a hierarchy?

**Comment by DariLupea** [comment]
I know it`s a lot of dependence here. I thought that CheckSolution and UserGame both use a check method which work with check, so I linked  them. Now that you say, it doesn`t actually make sense, I tried to make specific classes for each 'operation', but the conexions are quite strong.
I don`t really know  how to figure it out. 'UserGame' and 'GameGenerator' should be the 'main' classes?

**Comment by Alex-Cosma** [comment]
Well, you know, having specific classes for operations is quite fine! It's a good idea, but I do not think you need to have this hierarchy. I think you should use something like composition for achieving what you want, not inheritance

**Comment by DariLupea** [comment]
OK, I`ll try to  fix this somehow

**Comment by DariLupea** [comment]
Hei! Am o intrebare... exista vreo modalitate prin care sa recuperez un
proiect? L-am sters din greseala din folderul meu cu proiecte Java si nu il
mai gasesc nici in Recycle Bin acum.

On Sun, Dec 20, 2015 at 9:43 PM, Cosma Alex <notifications@github.com>
wrote:

> Well, you know, having specific classes for operations is quite fine! It's
> a good idea, but I do not think you need to have this hierarchy. I think
> you should use something like composition for achieving what you want, not
> inheritance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-166152802>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by DariLupea** [comment]
Am rezolvat, scuze

On Mon, Dec 21, 2015 at 1:19 PM, Dari Lupea <dari.lupea@gmail.com> wrote:

> Hei! Am o intrebare... exista vreo modalitate prin care sa recuperez un
> proiect? L-am sters din greseala din folderul meu cu proiecte Java si nu il
> mai gasesc nici in Recycle Bin acum.
>
> On Sun, Dec 20, 2015 at 9:43 PM, Cosma Alex <notifications@github.com>
> wrote:
>
>> Well, you know, having specific classes for operations is quite fine!
>> It's a good idea, but I do not think you need to have this hierarchy. I
>> think you should use something like composition for achieving what you
>> want, not inheritance
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-166152802>
>> .
>>
>
>
>
> --
>
>
>
> *Dariana Lupea*
>
> 0754696609/ dari.lupea@gmail.com
>
>
> *Organizatia Studentilor din Universitatea Tehnica*
>
> Office: 0742.366.442 / Fax: office@osut.org
>
> str. Ceahlau, nr. 72, Cluj-Napoca
>
> www.osut.org <http://osut.org/>
>
>
>
>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
But now you have duplicate code in the classes, I don't think I understand what you are trying to do there :pensive:

**Comment by DariLupea** [comment]
I need those methods for both classes, I don`t know how to implement this.
Would it be ok if I had only one class for the game?

On Mon, Dec 21, 2015 at 8:28 PM, Cosma Alex <notifications@github.com>
wrote:

> But now you have duplicate code in the classes, I don't think I understand
> what you are trying to do there [image: :pensive:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-166396816>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by DariLupea** [comment]
First I wrote a single  class, then I tried to split it  into classes with
specific operations but it seems to be more difficult than I thought

On Mon, Dec 21, 2015 at 9:46 PM, Dari Lupea <dari.lupea@gmail.com> wrote:

> I need those methods for both classes, I don`t know how to implement this.
> Would it be ok if I had only one class for the game?
>
> On Mon, Dec 21, 2015 at 8:28 PM, Cosma Alex <notifications@github.com>
> wrote:
>
>> But now you have duplicate code in the classes, I don't think I
>> understand what you are trying to do there [image: :pensive:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-166396816>
>> .
>>
>
>
>
> --
>
>
>
> *Dariana Lupea*
>
> 0754696609/ dari.lupea@gmail.com
>
>
> *Organizatia Studentilor din Universitatea Tehnica*
>
> Office: 0742.366.442 / Fax: office@osut.org
>
> str. Ceahlau, nr. 72, Cluj-Napoca
>
> www.osut.org <http://osut.org/>
>
>
>
>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Depending on what it does, it may be. I don't see the whole picture yet so I can't.. tell

**Comment by DariLupea** [comment]
Neither do I:)) I am still trying to figure out some stuff.  I started working at the GUI, because there I have at least an idea of what I want to see.

**Comment by Alex-Cosma** [comment]
Great! Things actually look pretty clean.
Ps: delete the old Sudoku projects from the folder if you don't need them any more so it won't be confusing for me when I pull your changes and have to import the project

**Comment by Alex-Cosma** [comment]
The game is so cuuute! Și ce frumos se highlight-uiesc pătrățelele :laughing:

**Comment by Alex-Cosma** [comment]
`public static int[][] game;` can actually be just `private` without even the static there.

**Comment by Alex-Cosma** [comment]
Other than this, no objections to the code. Lovely work!
Don't forget about the UML and again, happy new year.

**Comment by Alex-Cosma** [comment]
http://www.codeproject.com/Articles/90885/Sudoku-Game-in-Java

I downloaded the source code and it's identical to yours. I will thus invalidate your project. :disappointed:

**Comment by DariLupea** [comment]
I`m sorry... can I try to make another one?

On Fri, Jan 1, 2016 at 4:08 PM, Cosma Alex <notifications@github.com> wrote:

> http://www.codeproject.com/Articles/90885/Sudoku-Game-in-Java
>
> I downloaded the source code and it's identical to yours. I will thus
> invalidate your project. [image: :disappointed:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168312481>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
In 2 days..?

**Comment by DariLupea** [comment]
I`ll try... but I`m not sure if it`s ok to try this game again, because I
already have some ideas about how it should be done...


On Fri, Jan 1, 2016 at 5:34 PM, Cosma Alex <notifications@github.com> wrote:

> In 2 days..?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168315337>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Yea, so, I don't think there's much you can do now.

**Comment by DariLupea** [comment]
I`ll try...

On Fri, Jan 1, 2016 at 5:43 PM, Cosma Alex <notifications@github.com> wrote:

> Yea, so, I don't think there's much you can do now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168316079>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
You'll try what exactly?

**Comment by DariLupea** [comment]
To redo it. Maybe I could use only the interface and built the
functioning... Or try another game

On Fri, Jan 1, 2016 at 5:48 PM, Cosma Alex <notifications@github.com> wrote:

> You'll try what exactly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168316804>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Nu. Poate în restanțe, dar ținând cont că e vorba de copiat, poate la anul.

**Comment by Alex-Cosma** [comment]
Sau, îți alegi un cu totul alt joc, îmi zici acum ce, și îl faci de la 0 până poimâine seară.

**Comment by DariLupea** [comment]
Adica o sa am restanta la OOP? Nu inteleg...
As vrea sa aleg alt joc, ma uit acum in lista cu jocurile si iti spun

2016-01-01 17:55 GMT+01:00 Cosma Alex <notifications@github.com>:

> Sau, îți alegi un cu totul alt joc, îmi zici acum ce, și îl faci de la 0
> până poimâine seară.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168317017>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Ce nu înțelegi? Da, ai avea restanță la OOP pentru că nu ți-ai trece laboratorul.

**Comment by DariLupea** [comment]
Atunci o sa aleg varianta cu jocul. Dar chiar nu stiu ce joc sa aleg, incat
sa reusesc sa il termin asa repede. Doar din cele care sunt pe site mai pot
alege?

2016-01-01 18:03 GMT+01:00 Cosma Alex <notifications@github.com>:

> Ce nu înțelegi? Da, ai avea restanță la OOP pentru că nu ți-ai trece
> laboratorul.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168317247>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Ai alte idei?

**Comment by DariLupea** [comment]
Spanzutaroarea ar fi ok? Si sa am o lista de cuvinte, iar user-ul sa
ghiceasca. Nu stiu cum se numeste in engleza. Altceva nu imi vine acum in
minte. Iar la interfata sa imi construiesc corpul, cu cap, maini, picioare,
etc...

On Fri, Jan 1, 2016 at 5:42 PM, Dari Lupea <dari.lupea@gmail.com> wrote:

> I`ll try... but I`m not sure if it`s ok to try this game again, because I
> already have some ideas about how it should be done...
>
>
> On Fri, Jan 1, 2016 at 5:34 PM, Cosma Alex <notifications@github.com>
> wrote:
>
>> In 2 days..?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168315337>
>> .
>>
>
>
>
> --
>
>
>
> *Dariana Lupea*
>
> 0754696609/ dari.lupea@gmail.com
>
>
> *Organizatia Studentilor din Universitatea Tehnica*
>
> Office: 0742.366.442 / Fax: office@osut.org
>
> str. Ceahlau, nr. 72, Cluj-Napoca
>
> www.osut.org <http://osut.org/>
>
>
>
>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>
> <http://osut.org/>
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Hangman e în engleză. E prea simplu

**Comment by DariLupea** [comment]
Tic-Tac-Toe?

2016-01-01 18:35 GMT+01:00 Cosma Alex <notifications@github.com>:

> Hangman e în engleză. E prea simplu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168318698>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Tic Tac Toe e ok, dar trebuie să-l faci cu AI care să joace perfect (adică cu un minmax algorithm), asta era cerința la Tic Tac Toe pentru cei care au vrut să-l facă.

**Comment by DariLupea** [comment]
Nu stiu cum ar trebui abordat cu AI... Jocul Puzzle e ok?

2016-01-01 18:45 GMT+01:00 Cosma Alex <notifications@github.com>:

> Tic Tac Toe e ok, dar trebuie să-l faci cu AI care să joace perfect (adică
> cu un minmax algorithm), asta era cerința la Tic Tac Toe pentru cei care au
> vrut să-l facă.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168320470>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Puzzle.. Adică să faci un puzzle?

**Comment by DariLupea** [comment]
da... sa am bucati de imagini pe care sa le pun in ordinea corecta

On Fri, Jan 1, 2016 at 6:59 PM, Cosma Alex <notifications@github.com> wrote:

> Puzzle.. Adică să faci un puzzle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168321022>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Comment by Alex-Cosma** [comment]
Bine, vezi ce poți face până poimâine.

**Comment by DariLupea** [comment]
Ok.

On Fri, Jan 1, 2016 at 7:11 PM, Cosma Alex <notifications@github.com> wrote:

> Bine, vezi ce poți face până poimâine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OOP-2015-Sem1/OOP-2015/pull/72#issuecomment-168325169>
> .
>



-- 



*Dariana Lupea*

0754696609/ dari.lupea@gmail.com


*Organizatia Studentilor din Universitatea Tehnica*

Office: 0742.366.442 / Fax: office@osut.org

str. Ceahlau, nr. 72, Cluj-Napoca

www.osut.org <http://osut.org/>





<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

<http://osut.org/>

**Pull request merged**
