### PR TITLE
Proiect SNAKE intrebari

### PR DESCRIPTION
**Pull request by CalugarCatalina**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
First off, you can just take a look [here](https://github.com/OOP-2015-Sem1/OOP-2015/tree/master/Exam%20Problems%20-%20Solutions/Snake) to see how to use a controller linked with a frame and an action listener

**Comment by Alex-Cosma** [comment]
Careful, you have compilation errors.

**Comment by Alex-Cosma** [comment]
Also, if you're not using the class `BodyParts` you should delete it

**Comment by Alex-Cosma** [comment]
You should not set the values to those direction variables. They should be *constant*. The idea was to have a variable inside the `Snake` class which, yes, as you mentioned there, indicates its direction. However, you should simply set it like
`snake.setDirection(Constants.RIGHT);` 
or to whichever direction. You should not have to set them all to false and then set 1 to true.

**Comment by Alex-Cosma** [comment]
Also, the direction attribute in the `Snake` class should not be static

**Comment by Alex-Cosma** [comment]
The `Snake` object should not contain an attribute called `scr` which is a type `JButton`. The `Snake` class should model a snake, nothing more. It should not contain any references to food either maybe only as parameters to some method but in itself, it should not have any direct attributes related to food

**Comment by Alex-Cosma** [comment]
Also, I'm very curious how and why the `Snake` class extends `JPanel`. What was the idea here? I can't be a panel as a panel is a rectangle of sort and the `Snake` can have a weird shape, so why extend `JPanel`?

**Comment by Alex-Cosma** [comment]
You can of course take a look at how [this](https://github.com/OOP-2015-Sem1/OOP-2015/tree/master/Exam%20Problems%20-%20Solutions/Snake) is implemented. Steal some ideas from there.

**Comment by CalugarCatalina** [comment]
I deleted the BodyParts.java class and I also deleted other classes, but I guess I didn't update the project right on git. I made the direction as you said, I'll put the project again.

I used Snake extends JPanel because I add as a panel in GameFrame.java the snakePanel which is the Snake object and also the repaint() method does not work without JPanel. Shall I change it somehow in order not to extend JPanel?

**Comment by Alex-Cosma** [comment]
I don't understand why you now group the two together. Create a class `Snake` and a class `Food` or whatnot, and split them. Single responsibility, remember?
`A snake is not a JPanel.` -> so long as this holds, you should not write something like `Snake extends JPanel`. It is simply not true.

**Comment by Alex-Cosma** [comment]
`currentDirection` should not be static - create a getter and setter for it and place it in the new `Snake` class

**Comment by Alex-Cosma** [comment]
```
	private Random random;
```
I do not believe this should be a class field but rather a local variable in whichever function it is needed

**Comment by Alex-Cosma** [comment]
```
	public static JButton scr;
```
Again, shouldn't be static. You can create a method in the `GameFrame` class which simply sets the score to a certain value

**Comment by Alex-Cosma** [comment]
That would be all, for now

**Comment by Alex-Cosma** [comment]
The problem is that you have two instances of the class `Snake`. One in the `Screen` class, and one in the `KeyController` class. They are, of course, independent! Hence, if you do not have this `currentDirection` static (common amongst all instances), if you change it in one place, it will not change in the other. You might want to keep one instance of `Snake` in the `GameFrame` class for example and pass it as constructor parameters to both `Screen` and `KeyController`. Just one idea, you can come up with another

**Comment by Alex-Cosma** [comment]
Everything else looks much better :smile:

**Comment by CalugarCatalina** [comment]
snakeuml
This UML is ok?

**Comment by Alex-Cosma** [comment]
Yup

**Comment by CalugarCatalina** [comment]
I think I'm retarded. Does the project I uploaded today appear? Everywhere on Git is written that I last committed 6 days ago but in my repository folder appears that the game committed.

**Comment by Alex-Cosma** [comment]
Nope, not here.

**Comment by Alex-Cosma** [comment]
Make sure to push it

**Comment by Alex-Cosma** [comment]
I can close this pull request if you think it'll help

**Comment by CalugarCatalina** [comment]
The 3rd time is the lucky one..

**Comment by Alex-Cosma** [comment]
There we go

**Pull request merged**
