### PR TITLE
This commit also contains an older homework, but this is not the main concern 

### PR DESCRIPTION
**Pull request by CorinaAlb**
Here I have a problem in Solitaire Java Project. Shortly, I don't know how to implement the cards movement. Can you please give me some hint?
I'll explain you what I've done so far: I have the Main class Solitaire where I create all the elements in the GUI, as an extension of JLayeredPane. I also have a SharedPreferences class where I monitor which and if a card is selected and some other features like the pile of cards the selected-blue- card is part of and the pile the destination card is part of. Right now I cannot add anithing to the destination pile and I'm kind of stuck here, so please, I need some help :D.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
You don't have to implement it with drag'n'drop!

**Comment by Alex-Cosma** [comment]
Click -> Click is just fine

**Comment by Alex-Cosma** [comment]
But I do not understand... you have:
`GUIFoundadtionClubs`
`GUIFoundadtionDiamonds`
`GUIFoundadtionHearts`
`GUIFoundadtionSpades`

Which contain the exact same code! Why not just create 4 instances of 1 object? I don't understand

**Comment by Alex-Cosma** [comment]
All the fields from `Solitaire` class should be made non-static. Also, all the methods as well. You can have the `main` method in a different class and move the code from the current main method in the constructor of `Solitaire` and in the new main class, you'll simply call `new Solitaire();`

**Comment by Alex-Cosma** [comment]
I think you have quite a lot to work here!

**Comment by Alex-Cosma** [comment]
http://www.javased.com/index.php?source_dir=javasol/src/com/fbergeron/#

Unfortunately, your code is copied from here so I will invalidate your project.

**Comment by CorinaAlb** [comment]
ok, so now what's the procedure? I understand i have to take the exam in the session of reexamination, but what about the project?

**Comment by Alex-Cosma** [comment]
No, from what I know, you can take both the course exam and the lab test in this session and only do the project presentation (different project) in the re-examination session.

**Comment by CorinaAlb** [comment]
oh, ok, great ! should I take a different project?

**Comment by Alex-Cosma** [comment]
Yep, let's talk at the lab this week.

**Comment by CorinaAlb** [comment]
ok, great!

**Pull request merged**
