### PR TITLE
InternetBanking Project

### PR DESCRIPTION
**Pull request by gergo13**
Unfortunately it's still far from working properly.
(Ignore the first 3 commits)

### CODE REVIEW

**Comment by gergo13** [comment]
The GUI is nearly done, I still have to add/modify a few JPanels, but that's not an issue. The part where the user manages his bank account is still missing (the interface/classes/methods are already there, but without implementation).
I wanted to connect to a database (Microsoft SQL Server 2014), but I don't know how (I tried several methods and read more tutorials but no luck).

Could you help me?
If I manage to connect to the database, I would be able to manage the bank accounts/users (or whatever such an application needs) using SQL queries.

Thanks,
Gergő

**Comment by Alex-Cosma** [comment]
I think you should try out `MySQL` instead of `MSSQL`. From my experience, it'll work quicker, but I cannot help you with it.

**Comment by gergo13** [comment]
I will try that. Until then, I will add most of the features, such that even in the worst case only the 'SQL part' should be missing.
I hope the 'Java part' of the project is not so bad... 

Thanks,
Gergő

**Comment by Alex-Cosma** [comment]
No, the java part is not so bad :blush:

**Pull request merged**
