### PR TITLE
This is my project!

### PR DESCRIPTION
**Pull request by patric1226**
I forgot about the instructions. Move with arrows and shoot with space.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I don't understand. There is absolutely no difference between `EntityA` and `EntityB` yet they are different interfaces. Why!?

**Comment by Alex-Cosma** [comment]
So you have a very high FPS rate which is so very unnecessary! Just use this code, as I previously told [one of your colleagues](https://github.com/OOP-2015-Sem1/OOP-2015/pull/73)

```
	public void run() {
		init();
		long lastTime = System.currentTimeMillis();
		final double amountOfTicks = 60.0;
		double ns = 1000 / amountOfTicks;
		double delta = 0;
		int updates = 0;
		int frames = 0;
		long timer = System.currentTimeMillis();

		while (running) {
			long now = System.currentTimeMillis();
			delta += (now - lastTime) / ns;
			lastTime = now;
			if (delta >= 1) {
				tick();
				updates++;
				delta--;
				
			}
			try {
				Thread.sleep(18);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			render();
			frames++;

			if (System.currentTimeMillis() - timer > 1000) {
				timer += 1000;
				System.out.println(updates + " Ticks, FPS " + frames);
				updates = 0;
				frames = 0;
			}
		}
		stop();

	}
```

**Comment by Alex-Cosma** [comment]
Besides the whole `Entity` thing which baffles me still, format your code and make your ship destroyable!
Oh and do a better job splitting it into more packages.

**Comment by patric1226** [comment]
EntityA represents the Bullet and the Spaceship and Entity B is for the enemy. Is easier to see the collision this way. A entitys don't colide with eachother, they colide only with B entitys(enemy).

**Comment by Alex-Cosma** [comment]
No, it's not "easier to see the collision this way". Conceptually, it's nonsense! Create one single interface, `Entity` and that's it. It doesn't matter which entities don't intercept with which, you'll pass instances not types as parameters.

**Comment by patric1226** [comment]
I didn't manage to make the collision between the space ship and the enemy :( I deleted the EntityB interface and i splitted the application in 4 packages. :D

**Pull request merged**
